In [1]:
!pip install biopython biotite nglview -q

import os
import shutil
import requests
import numpy as np
from pathlib import Path

from Bio.PDB import PDBParser, PDBIO, Select

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.2/26.2 MB 66.8 MB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 91.4 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.0/58.0 MB 33.3 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 87.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.2/17.2 MB 83.7 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 109.4 MB/s eta 0:00:0000:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 915.3/915.3 kB 35.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.5/77.5 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 kB 28.1 MB/s eta 0:00:00
  Building wheel for nglview (pyproject.toml) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyterlab-lsp 3.10.2 requires jupyterlab<4.0.0a0,>=3.1.0, but you have jupyterlab 4.6.3 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.20.0 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
jupyter-kernel-gateway 2.5.2 requires notebook<7.0,>=5.7.6, but you have notebook 7.6.2 which is incompatible.

In [2]:
import pandas as pd
from pathlib import Path

In [3]:
import pandas as pd

file = "/kaggle/input/datasets/tura76/sabdab-dataset/sabdab_summary_all.tsv"

cols = [
    "pdb", "Hchain", "Lchain",
    "antigen_chain", "antigen_type",
    "antigen_name", "resolution", "method"
]

df_sabdab = pd.read_csv(file, sep="\t", usecols=cols)

with_antigen = df_sabdab[
    df_sabdab["antigen_chain"].notna() &
    (df_sabdab["antigen_chain"].astype(str).str.strip() != "")
]

print("Total SAbDab entries:", len(df_sabdab))
print("Entries with antigen:", len(with_antigen))

display(with_antigen.head(20))

Total SAbDab entries: 20700
Entries with antigen: 16560

,pdb,Hchain,Lchain,antigen_chain,antigen_type,antigen_name,resolution,method
0,10gh,C,B,A,protein,proto-oncogene tyrosine-protein kinase ros,3.06,ELECTRON MICROSCOPY
5,1a14,H,L,N,protein,neuraminidase,2.5,X-RAY DIFFRACTION
6,1a2y,B,A,C,protein,lysozyme,1.5,X-RAY DIFFRACTION
7,1a3l,H,L,L,Hapten,1-CARBOXY-1'-[(DIMETHYLAMINO)-CARBONYL]FERROCENE,1.95,X-RAY DIFFRACTION
8,1a3r,H,L,P,peptide,human rhinovirus capsid protein vp2,2.1,X-RAY DIFFRACTION
11,1a4k,B,A,B,Hapten,"[4-(4-ACETYLAMINO-PHENYL)-3,5-DIOXO-4-AZA-TRIC...",2.4,X-RAY DIFFRACTION
12,1a4k,H,L,H,Hapten,"[4-(4-ACETYLAMINO-PHENYL)-3,5-DIOXO-4-AZA-TRIC...",2.4,X-RAY DIFFRACTION
17,1a6v,H,L,H,Hapten,4-HYDROXY-3-NITROPHENYLACETYL-EPSILON-AMINOCAP...,1.8,X-RAY DIFFRACTION
18,1a6v,I,M,I,Hapten,4-HYDROXY-3-NITROPHENYLACETYL-EPSILON-AMINOCAP...,1.8,X-RAY DIFFRACTION
19,1a6v,J,N,J,Hapten,4-HYDROXY-3-NITROPHENYLACETYL-EPSILON-AMINOCAP...,1.8,X-RAY DIFFRACTION
20,1a6w,H,L,H,Hapten,4-HYDROXY-5-IODO-3-NITROPHENYLACETYL-EPSILON-A...,2.0,X-RAY DIFFRACTION
26,1a8j,NaN,H,L,Hapten,N-L-ALPHA-ASPARTYL L-PHENYLALANINE 1-METHYL ESTER,2.7,X-RAY DIFFRACTION
27,1a8j,NaN,L,L,Hapten,N-L-ALPHA-ASPARTYL L-PHENYLALANINE 1-METHYL ESTER,2.7,X-RAY DIFFRACTION
28,1acy,H,L,P,peptide,hiv-1 gp120 (mn isolate),3.0,X-RAY DIFFRACTION
33,1adq,H,L,A,protein,igg4 rea fc,3.15,X-RAY DIFFRACTION
35,1afv,H,L,A,protein,human immunodeficiency virus type 1 capsidprot...,3.7,X-RAY DIFFRACTION
36,1afv,K,M,B,protein,human immunodeficiency virus type 1 capsidprot...,3.7,X-RAY DIFFRACTION
37,1ahw,B,A,C,protein,tissue factor,3.0,X-RAY DIFFRACTION
38,1ahw,E,D,F,protein,tissue factor,3.0,X-RAY DIFFRACTION
39,1ai1,H,L,P,peptide,aib142,2.8,X-RAY DIFFRACTION

In [4]:
import json
from pathlib import Path

TARGETS = Path("/kaggle/input/datasets/potatoguy44/sabdab2-nanobodies/targets_vhh.json")

with open(TARGETS, "r") as f:
    targets = json.load(f)

print(type(targets))

if isinstance(targets, dict):
    print("Number of entries:", len(targets))
    print("\nFirst entry:")
    first_key = next(iter(targets))
    print(first_key)
    print(targets[first_key])

elif isinstance(targets, list):
    print("Number of entries:", len(targets))
    print("\nFirst entry:")
    print(targets[0])

<class 'list'>
Number of entries: 597

First entry:
{'instance': 'pdb_000010zo_A_+', 'pdb': '10ZO', 'H': 'A', 'sabdab_id': 'H006BL0000', 'cdrh3_cluster': 'pdb_000010zo_A_+', 'hseq': 'GLVQAGESLRLSCAVPPEVFDIRTVAWYRQVPLGKGRELLSSITPWNKTTYEDSVKDRFTISRDNAKYTVYLQMNDLKPEDTAVYYCAQGWGIASMRYWGQGTQVTVSS', 'numbering': 'IMGT', 'atoms': ['N', 'CA', 'C', 'CB'], 'cdr1': [16, 24], 'cdr2': [42, 49], 'cdr3': [87, 98], 'CDRH1': 'PEVFDIRT', 'CDRH2': 'ITPWNKT', 'CDRH3': 'AQGWGIASMRY', 'resolution': '1.65', 'method': 'XRAY', 'holo': 'True', 'ab_split': 'train', 'PDBdepo': '2026-02-12', 'n_resolved': 109, 'hca': [[[88.824, 104.373, -5.191], [88.668, 103.04, -5.727], [89.946, 102.392, -6.233], None], [[90.696, 103.135, -7.059], [91.981, 102.695, -7.596], [93.088, 103.294, -6.749], [92.164, 103.111, -9.056]], [[93.839, 102.436, -6.076], [94.872, 102.886, -5.169], [96.124, 102.042, -5.386], [94.371, 102.85, -3.714]], [[97.216, 102.501, -4.8], [98.51, 101.857, -4.944], [98.85, 101.089, -3.672], [99.596, 102.898, -5.233]], [[99.654, 100.039, -3.819], [100.069, 99.26, -2.659], [100.732, 100.168, -1.625], [101.023, 98.141, -3.088]], [[100.397, 99.95, -0.348], [100.876, 100.783, 0.733], [100.0, 101.974, 1.054], None], [[98.963, 102.224, 0.266], [98.048, 103.316, 0.54], [96.894, 102.805, 1.399], [97.562, 103.94, -0.764]], [[95.979, 103.706, 1.735], [94.865, 103.398, 2.621], [93.539, 103.724, 1.946], [94.969, 104.174, 3.94]], [[92.491, 103.05, 2.418], [91.118, 103.315, 2.015], [90.221, 103.142, 3.226], [90.638, 102.365, 0.929]], [[89.236, 104.023, 3.354], [88.255, 103.985, 4.428], [86.887, 103.776, 3.798], [88.296, 105.286, 5.232]], [[86.238, 102.663, 4.132], [84.904, 102.383, 3.628], [83.886, 102.65, 4.726], [84.786, 100.936, 3.146]], [[82.703, 103.112, 4.328], [81.678, 103.516, 5.276], [80.372, 102.785, 4.991], [81.451, 105.029, 5.225]], [[79.607, 102.562, 6.06], [78.362, 101.801, 6.007], [77.331, 102.524, 6.864], [78.584, 100.37, 6.497]], [[76.355, 103.164, 6.222], [75.315, 103.861, 6.962], [74.344, 102.857, 7.573], [74.566, 104.833, 6.05]], [[74.044, 103.037, 8.85], [73.092, 102.204, 9.577], [71.955, 103.105, 10.017], [73.734, 101.513, 10.795]], [[70.693, 102.722, 9.814], [69.58, 103.577, 10.24], [69.683, 103.888, 11.722], [68.339, 102.726, 9.93]], [[69.466, 105.146, 12.114], [69.657, 105.517, 13.528], [68.779, 104.731, 14.488], [69.311, 107.013, 13.546]], [[67.596, 104.293, 14.051], [66.702, 103.567, 14.949], [67.289, 102.228, 15.383], [65.344, 103.346, 14.281]], [[68.154, 101.629, 14.564], [68.706, 100.306, 14.822], [70.218, 100.339, 15.018], [68.328, 99.32, 13.697]], [[70.804, 101.53, 15.157], [72.251, 101.619, 15.307], [72.741, 100.934, 16.582], [72.683, 103.078, 15.273]], [[71.918, 100.886, 17.629], [72.277, 100.172, 18.849], [71.68, 98.767, 18.902], [71.861, 100.984, 20.075]], [[71.25, 98.235, 17.755], [70.643, 96.913, 17.661], [71.436, 95.998, 16.732], [69.169, 97.006, 17.203]], [[71.691, 96.445, 15.507], [72.237, 95.55, 14.5], [73.745, 95.379, 14.627], [71.901, 96.059, 13.099]], [[74.196, 94.139, 14.467], [75.593, 93.878, 14.148], [75.862, 94.22, 12.688], [75.924, 92.414, 14.44]], [[77.062, 94.73, 12.421], [77.456, 95.135, 11.077], [78.712, 94.368, 10.686], [77.675, 96.662, 10.992]], [[78.737, 93.875, 9.447], [79.835, 93.056, 8.957], [80.287, 93.525, 7.578], [79.433, 91.571, 8.9]], [[81.592, 93.446, 7.349], [82.19, 93.742, 6.057], [82.575, 92.451, 5.36], [83.42, 94.643, 6.216]], [[82.331, 92.402, 4.048], [82.602, 91.237, 3.23], [83.377, 91.692, 2.008], [81.319, 90.529, 2.753]], [[83.98, 90.731, 1.328], [84.542, 91.059, 0.027], [84.494, 89.847, -0.888], [85.97, 91.594, 0.154]], [[84.354, 90.122, -2.177], [84.34, 89.086, -3.203], [85.589, 89.29, -4.043], [83.08, 89.153, -4.058]], [[86.56, 88.397, -3.878], [87.831, 88.484, -4.591], [87.589, 88.037, -6.029], [88.929, 87.655, -3.899]], [[88.452, 88.413, -6.975], [88.133, 88.189, -8.396], [87.846, 86.739, -8.772], [89.381, 88.725, -9.104]], [[88.51, 85.766, -8.154], [88.297, 84.359, -8.474], [87.611, 83.657, -7.303], [89.623, 83.689, -8.833]], [[86.628, 84.327, -6.708], [86.03, 83.897, -5.454], [84.605, 83.389, -5.642], None], [[84.316, 82.264, -4.996], [82.962, 81.717, -4.916], [82.286, 82.36, -3.709], [83.002, 80.194, -4.808]], [[81.573, 83.453, -3.947], [80.84, 84.137, -2.901], [81.607, 85.26, -2.228], None], [[80.965, 85.809, -1.203], [81.519, 86.904, -0.418], [82.089, 86.352, 0.88], [80.444, 87.954, -0.135]], [[83.327, 86.722, 1.191], [83.999, 86.224, 2.381], [83.9, 87.259, 3.495], [85.465, 85.87, 2.091]], [[83.616, 86.782, 4.704], [83.495, 87.672, 5.844], [84.868, 88.2, 6.228], [82.863, 86.931, 7.02]], [[84.977, 89.519, 6.378], [86.231, 90.155, 6.765], [86.246, 90.574, 8.226], [86.492, 91.389, 5.904]], [[85.158, 91.174, 8.692], [85.135, 91.798, 10.003], [83.685, 92.036, 10.402], [85.921, 93.117, 9.992]], [[83.43, 92.065, 11.707], [82.097, 92.4, 12.188], [82.221, 93.161, 13.498], [81.22, 91.159, 12.383]], [[81.199, 93.955, 13.804], [81.166, 94.727, 15.044], [79.739, 94.745, 15.585], [81.716, 96.154, 14.831]], [[79.589, 94.395, 16.847], [78.294, 94.491, 17.496], [78.092, 95.899, 18.025], [78.207, 93.49, 18.64]], [[76.856, 96.277, 18.356], [76.637, 97.607, 18.938], [77.382, 97.831, 20.254], [75.114, 97.659, 19.13]], [[77.888, 96.775, 20.89], [78.623, 96.853, 22.147], [80.13, 96.748, 21.929], [78.09, 95.772, 23.092]], [[80.555, 96.836, 20.665], [81.948, 96.905, 20.235], [82.707, 95.606, 20.477], [82.68, 98.093, 20.865]], [[82.017, 94.478, 20.357], [82.68, 93.2, 20.157], [83.022, 93.102, 18.677], [81.801, 92.028, 20.576]], [[84.296, 92.899, 18.373], [84.738, 92.836, 16.99], [85.315, 91.462, 16.678], [85.794, 93.9, 16.69]], [[85.237, 91.08, 15.404], [85.902, 89.894, 14.894], [86.646, 90.281, 13.626], [84.916, 88.76, 14.561]], [[87.723, 89.556, 13.336], [88.489, 89.796, 12.122], [88.898, 88.48, 11.492], [89.747, 90.627, 12.389]], [[88.823, 88.425, 10.167], [89.467, 87.349, 9.44], [90.975, 87.478, 9.602], [89.066, 87.388, 7.966]], [[91.635, 86.34, 9.812], [93.03, 86.356, 10.239], [93.949, 86.989, 9.202], [93.486, 84.933, 10.568]], [[93.649, 86.834, 7.917], [94.563, 87.35, 6.904], [94.461, 88.862, 6.712], [94.334, 86.645, 5.561]], [[93.504, 89.537, 7.351], [93.379, 90.987, 7.262], [93.503, 91.675, 8.612], [92.059, 91.404, 6.578]], [[93.664, 90.92, 9.701], [93.586, 91.511, 11.033], [94.683, 92.538, 11.286], [93.643, 90.414, 12.096]], [[95.81, 92.447, 10.597], [96.903, 93.363, 10.873], [96.87, 94.603, 9.989], [98.242, 92.632, 10.74]], [[95.839, 94.764, 9.167], [95.715, 95.976, 8.365], [94.318, 96.578, 8.339], [96.181, 95.705, 6.931]], [[93.278, 95.845, 8.739], [91.896, 96.304, 8.693], [91.376, 96.503, 10.108], [90.979, 95.295, 7.989]], [[90.665, 97.606, 10.331], [90.05, 97.854, 11.63], [88.631, 98.362, 11.425], [90.862, 98.87, 12.447]], [[87.674, 97.773, 12.144], [86.271, 98.166, 12.064], [85.951, 99.044, 13.272], [85.364, 96.911, 11.99]], [[85.086, 100.04, 13.08], [84.7, 100.926, 14.173], [83.327, 101.527, 13.904], [85.711, 102.055, 14.372]], [[82.7, 102.022, 14.973], [81.391, 102.663, 14.916], [81.521, 104.147, 15.229], [80.417, 102.026, 15.915]], [[80.802, 104.976, 14.478], [80.734, 106.412, 14.738], [79.295, 106.741, 15.128], [81.198, 107.237, 13.539]], [[79.074, 106.871, 16.436], [77.748, 107.129, 16.983], [77.123, 108.395, 16.398], [77.841, 107.231, 18.506]], [[77.887, 109.492, 16.334], [77.309, 110.757, 15.877], [76.842, 110.685, 14.431], [78.311, 111.899, 16.027]], [[77.503, 109.877, 13.604], [77.175, 109.793, 12.19], [76.418, 108.525, 11.821], [78.45, 109.906, 11.349]], [[76.111, 107.666, 12.795], [75.361, 106.428, 12.563], [75.98, 105.613, 11.431], [73.889, 106.729, 12.291]], [[77.298, 105.444, 11.51], [78.082, 104.842, 10.445], [79.074, 103.853, 11.041], [78.817, 105.927, 9.64]], [[79.351, 102.789, 10.291], [80.386, 101.815, 10.62], [81.475, 101.931, 9.564], [79.813, 100.386, 10.67]], [[82.717, 102.139, 10.0], [83.845, 102.284, 9.087], [84.688, 101.012, 9.04], [84.733, 103.466, 9.493]], [[85.28, 100.757, 7.875], [86.366, 99.792, 7.749], [87.588, 100.568, 7.276], [86.031, 98.661, 6.777]], [[88.566, 100.737, 8.157], [89.814, 101.393, 7.792], [90.78, 100.333, 7.283], [90.416, 102.141, 8.984]], [[91.178, 100.451, 6.02], [92.133, 99.545, 5.398], [93.456, 100.283, 5.233], [91.596, 99.046, 4.057]], [[94.487, 99.827, 5.939], [95.807, 100.448, 5.878], [96.806, 99.532, 5.179], [96.324, 100.791, 7.284]], [[97.85, 100.128, 4.609], [98.939, 99.37, 3.989], [98.399, 98.342, 2.99], [99.797, 98.689, 5.059]], [[97.622, 98.832, 2.034], [96.897, 97.937, 1.14], [97.854, 97.149, 0.244], [95.896, 98.73, 0.296]], [[97.428, 95.95, -0.134], [98.213, 95.008, -0.917], [97.4, 94.529, -2.11], [98.637, 93.801, -0.068]], [[98.062, 94.06, -3.174], [97.306, 93.599, -4.353], [96.278, 92.536, -4.031], [98.4, 93.057, -5.278]], [[96.521, 91.703, -3.016], [95.55, 90.676, -2.657], [94.27, 91.254, -2.069], [96.171, 89.676, -1.681]], [[94.228, 92.56, -1.795], [93.012, 93.213, -1.325], [92.108, 93.672, -2.458], [93.356, 94.412, -0.441]], [[92.54, 93.536, -3.712], [91.671, 93.842, -4.839], [90.423, 92.973, -4.78], [92.427, 93.608, -6.139]], [[89.255, 93.608, -4.685], [87.996, 92.876, -4.529], [86.837, 93.866, -4.582], [87.944, 92.091, -3.21]], [[85.62, 93.327, -4.553], [84.419, 94.123, -4.335], [84.028, 93.98, -2.875], [83.266, 93.682, -5.249]], [[83.866, 95.107, -2.194], [83.583, 95.13, -0.765], [82.119, 95.47, -0.505], [84.497, 96.137, -0.066]], [[81.5, 94.738, 0.426], [80.1, 94.922, 0.775], [79.937, 95.007, 2.285], [79.235, 93.755, 0.31]], [[78.964, 95.809, 2.712], [78.509, 95.862, 4.095], [77.194, 95.102, 4.224], [78.31, 97.309, 4.562]], [[76.982, 94.488, 5.39], [75.715, 93.837, 5.685], [75.409, 94.064, 7.156], [75.746, 92.331, 5.371]], [[74.126, 93.96, 7.506], [73.661, 94.2, 8.865], [72.636, 93.139, 9.253], [73.028, 95.591, 9.005]], [[72.612, 92.794, 10.535], [71.653, 91.814, 11.01], [71.978, 91.374, 12.424], None], [[71.286, 90.316, 12.855], [71.438, 89.848, 14.225], [72.669, 88.978, 14.415], [70.195, 89.065, 14.668]], [[73.113, 88.305, 13.361], [74.247, 87.404, 13.435], [74.639, 87.022, 12.024], None], [[75.676, 86.188, 11.922], [76.3, 85.93, 10.623], [75.33, 85.23, 9.678], [77.604, 85.125, 10.795]], [[74.54, 84.282, 10.191], [73.613, 83.562, 9.326], [72.414, 84.402, 8.92], [73.118, 82.28, 10.005]], [[72.197, 85.552, 9.558], [71.049, 86.402, 9.26], [71.483, 87.778, 8.767], [70.136, 86.521, 10.489]], [[72.667, 87.86, 8.163], [73.145, 89.106, 7.589], [72.312, 89.455, 6.372], [74.617, 88.996, 7.211]], [[71.741, 90.649, 6.384], [70.938, 91.14, 5.272], [71.2, 92.637, 5.163], [69.462, 90.766, 5.456]], [[70.284, 93.347, 4.511], [70.398, 94.793, 4.348], [71.7, 95.165, 3.645], [70.279, 95.508, 5.696]], [[72.07, 94.37, 2.648], [73.341, 94.558, 1.965], [73.436, 95.935, 1.328], [73.529, 93.477, 0.905]], [[74.582, 96.572, 1.519], [74.855, 97.831, 0.867], [75.411, 97.618, -0.524], None], [[75.576, 98.724, -1.238], [76.143, 98.662, -2.575], [77.603, 98.241, -2.506], [76.013, 100.019, -3.268]], [[78.009, 97.379, -3.434], [79.4, 96.983, -3.498], [80.296, 98.128, -3.931], None], [[81.511, 98.136, -3.382], [82.559, 99.09, -3.731], [83.711, 98.312, -4.342], [83.063, 99.856, -2.501]], [[84.083, 98.657, -5.576], [85.226, 98.024, -6.211], [86.522, 98.688, -5.764], [85.105, 98.112, -7.729]], [[87.478, 97.87, -5.346], [88.783, 98.332, -4.892], [89.832, 97.556, -5.665], [88.967, 98.122, -3.375]], [[90.747, 98.272, -6.319], [91.865, 97.641, -6.993], [93.163, 98.227, -6.465], [91.779, 97.813, -8.51]], [[94.062, 97.34, -6.056], [95.359, 97.69, -5.503], [96.406, 97.423, -6.57], [95.676, 96.874, -4.249]], [[96.966, 98.485, -7.151], [98.023, 98.317, -8.141], [99.35, 98.142, -7.423], [98.085, 99.511, -9.095]], [[100.13, 97.154, -7.851], [101.379, 96.834, -7.164], [102.316, 98.039, -7.146], [102.065, 95.636, -7.823]]]}

In [5]:
print(json.dumps(
    targets if isinstance(targets, list) else dict(list(targets.items())[:2]),
    indent=2
)[:5000])

[
  {
    "instance": "pdb_000010zo_A_+",
    "pdb": "10ZO",
    "H": "A",
    "sabdab_id": "H006BL0000",
    "cdrh3_cluster": "pdb_000010zo_A_+",
    "hseq": "GLVQAGESLRLSCAVPPEVFDIRTVAWYRQVPLGKGRELLSSITPWNKTTYEDSVKDRFTISRDNAKYTVYLQMNDLKPEDTAVYYCAQGWGIASMRYWGQGTQVTVSS",
    "numbering": "IMGT",
    "atoms": [
      "N",
      "CA",
      "C",
      "CB"
    ],
    "cdr1": [
      16,
      24
    ],
    "cdr2": [
      42,
      49
    ],
    "cdr3": [
      87,
      98
    ],
    "CDRH1": "PEVFDIRT",
    "CDRH2": "ITPWNKT",
    "CDRH3": "AQGWGIASMRY",
    "resolution": "1.65",
    "method": "XRAY",
    "holo": "True",
    "ab_split": "train",
    "PDBdepo": "2026-02-12",
    "n_resolved": 109,
    "hca": [
      [
        [
          88.824,
          104.373,
          -5.191
        ],
        [
          88.668,
          103.04,
          -5.727
        ],
        [
          89.946,
          102.392,
          -6.233
        ],
        null
      ],
      [
        [
          90.696,
          103.135,
          -7.059
        ],
        [
          91.981,
          102.695,
          -7.596
        ],
        [
          93.088,
          103.294,
          -6.749
        ],
        [
          92.164,
          103.111,
          -9.056
        ]
      ],
      [
        [
          93.839,
          102.436,
          -6.076
        ],
        [
          94.872,
          102.886,
          -5.169
        ],
        [
          96.124,
          102.042,
          -5.386
        ],
        [
          94.371,
          102.85,
          -3.714
        ]
      ],
      [
        [
          97.216,
          102.501,
          -4.8
        ],
        [
          98.51,
          101.857,
          -4.944
        ],
        [
          98.85,
          101.089,
          -3.672
        ],
        [
          99.596,
          102.898,
          -5.233
        ]
      ],
      [
        [
          99.654,
          100.039,
          -3.819
        ],
        [
          100.069,
          99.26,
          -2.659
        ],
        [
          100.732,
          100.168,
          -1.625
        ],
        [
          101.023,
          98.141,
          -3.088
        ]
      ],
      [
        [
          100.397,
          99.95,
          -0.348
        ],
        [
          100.876,
          100.783,
          0.733
        ],
        [
          100.0,
          101.974,
          1.054
        ],
        null
      ],
      [
        [
          98.963,
          102.224,
          0.266
        ],
        [
          98.048,
          103.316,
          0.54
        ],
        [
          96.894,
          102.805,
          1.399
        ],
        [
          97.562,
          103.94,
          -0.764
        ]
      ],
      [
        [
          95.979,
          103.706,
          1.735
        ],
        [
          94.865,
          103.398,
          2.621
        ],
        [
          93.539,
          103.724,
          1.946
        ],
        [
          94.969,
          104.174,
          3.94
        ]
      ],
      [
        [
          92.491,
          103.05,
          2.418
        ],
        [
          91.118,
          103.315,
          2.015
        ],
        [
          90.221,
          103.142,
          3.226
        ],
        [
          90.638,
          102.365,
          0.929
        ]
      ],
      [
        [
          89.236,
          104.023,
          3.354
        ],
        [
          88.255,
          103.985,
          4.428
        ],
        [
          86.887,
          103.776,
          3.798
        ],
        [
          88.296,
          105.286,
          5.232
        ]
      ],
      [
        [
          86.238,
          102.663,
          4.132
        ],
        [
          84.904,
          102.383,
          3.628
        ],
        [
          83.886,
          102.65,
          4.726
        ],
        [
          84.786,
          100.936,
          3.146
        ]
      ],
      [
        [
          82.703,
          103.112,
          4.328
        ],
        [
          81.678,
          103.516,
          5.276
        ],
        [
          80.372,
          102.785,
          4.991
        ],
        [
          81.451,
          105.029,
          5.225
        ]
      ],
      [
        [
          79.607,
          102.562,
          6.06
        ],
        [
          78.362,
          101.801,
          6.007
        ],
        [
          77.331,
          102.524,
          6.864
        ],
        [
          78.584,
          100.37,
          6.497
        ]
      ],
      [
        [
          76.355,
          103.164,
          6.222
        ],
        [
          75.315,
          103.861,
          6.962
        ],
        [
          74.344,
          102.857,
          7.573
        ],
        [
          74.566,
          104.833,
          6.05
        ]
      ],
      [
        [

In [6]:
import pandas as pd
targets_df = pd.DataFrame(targets)

print("Number of nanobodies:", len(targets_df))

print("\nColumns:")
print(targets_df.columns.tolist())

display(
    targets_df[
        ["pdb", "H", "sabdab_id", "hseq", "resolution", "method", "holo"]
    ].head()
)

Number of nanobodies: 597

Columns:
['instance', 'pdb', 'H', 'sabdab_id', 'cdrh3_cluster', 'hseq', 'numbering', 'atoms', 'cdr1', 'cdr2', 'cdr3', 'CDRH1', 'CDRH2', 'CDRH3', 'resolution', 'method', 'holo', 'ab_split', 'PDBdepo', 'n_resolved', 'hca']

,pdb,H,sabdab_id,hseq,resolution,method,holo
0,10ZO,A,H006BL0000,GLVQAGESLRLSCAVPPEVFDIRTVAWYRQVPLGKGRELLSSITPW...,1.65,XRAY,True
1,8F0K,N,H0098L0000,QVQLQESGGGLVQPGGSLRLSCAASGFTFSNYKMNWVRQAPGKGLE...,1.9,EM,True
2,7R73,A,H00EZL0000,VQLQESGGGLVQAGGSLRLSCTVSARTSSSHDMGWFRQAPGKEREF...,1.76,XRAY,True
3,7RG7,A,H00H1L0000,QVQLVESGGGLVQAGGSLRLSCAASRRSSRSWAMAWFRQAPGKERE...,1.83,XRAY,True
4,9UAQ,F,H05MGL0000,QVQLVESGGALVQPGGSLRLSCAASGFPVNRYSMRWYRQAPGKERE...,2.29,EM,True

In [7]:
merged = targets_df.merge(
    df_sabdab,
    left_on=["pdb", "H"],
    right_on=["pdb", "Hchain"],
    how="left",
    suffixes=("_vhh", "_sabdab")
)

print("Original nanobodies:", len(targets_df))
print("Matched with SAbDab:", merged["Hchain"].notna().sum())

display(
    merged[
        [
            "pdb",
            "H",
            "Hchain",
            "antigen_chain",
            "antigen_type",
            "antigen_name",
            "resolution_sabdab",
            "method_sabdab"
        ]
    ].head(20)
)

Original nanobodies: 597
Matched with SAbDab: 0

,pdb,H,Hchain,antigen_chain,antigen_type,antigen_name,resolution_sabdab,method_sabdab
0,10ZO,A,NaN,NaN,NaN,NaN,NaN,NaN
1,8F0K,N,NaN,NaN,NaN,NaN,NaN,NaN
2,7R73,A,NaN,NaN,NaN,NaN,NaN,NaN
3,7RG7,A,NaN,NaN,NaN,NaN,NaN,NaN
4,9UAQ,F,NaN,NaN,NaN,NaN,NaN,NaN
5,7D5B,D,NaN,NaN,NaN,NaN,NaN,NaN
6,7L6V,E,NaN,NaN,NaN,NaN,NaN,NaN
7,7XKA,B,NaN,NaN,NaN,NaN,NaN,NaN
8,7ZQT,F,NaN,NaN,NaN,NaN,NaN,NaN
9,7A5V,O,NaN,NaN,NaN,NaN,NaN,NaN
10,8W1V,F,NaN,NaN,NaN,NaN,NaN,NaN
11,9FAK,G,NaN,NaN,NaN,NaN,NaN,NaN
12,7AQG,C,NaN,NaN,NaN,NaN,NaN,NaN
13,9UYN,B,NaN,NaN,NaN,NaN,NaN,NaN
14,9RYF,C,NaN,NaN,NaN,NaN,NaN,NaN
15,7SAH,B,NaN,NaN,NaN,NaN,NaN,NaN
16,9EA9,F,NaN,NaN,NaN,NaN,NaN,NaN
17,8YA0,V,NaN,NaN,NaN,NaN,NaN,NaN
18,8TAO,D,NaN,NaN,NaN,NaN,NaN,NaN
19,9LR1,C,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Make copies so we don't modify the original data
targets_match = targets_df.copy()
sabdab_match = df_sabdab.copy()

# Normalize PDB IDs and chain IDs
targets_match["pdb_clean"] = (
    targets_match["pdb"]
    .astype(str)
    .str.strip()
    .str.upper()
)

targets_match["H_clean"] = (
    targets_match["H"]
    .astype(str)
    .str.strip()
    .str.upper()
)

sabdab_match["pdb_clean"] = (
    sabdab_match["pdb"]
    .astype(str)
    .str.strip()
    .str.upper()
)

sabdab_match["H_clean"] = (
    sabdab_match["Hchain"]
    .astype(str)
    .str.strip()
    .str.upper()
)

print("Example targets:")
display(targets_match[["pdb", "H", "pdb_clean", "H_clean"]].head())

print("\nExample SAbDab:")
display(sabdab_match[["pdb", "Hchain", "pdb_clean", "H_clean"]].head())

Example targets:

    pdb  H pdb_clean H_clean
0  10ZO  A      10ZO       A
1  8F0K  N      8F0K       N
2  7R73  A      7R73       A
3  7RG7  A      7RG7       A
4  9UAQ  F      9UAQ       F

Example SAbDab:

    pdb Hchain pdb_clean H_clean
0  10gh      C      10GH       C
1  12e8      H      12E8       H
2  12e8      P      12E8       P
3  15c8      H      15C8       H
4  1a0q      H      1A0Q       H

In [9]:
merged = targets_match.merge(
    sabdab_match,
    on=["pdb_clean", "H_clean"],
    how="left",
    suffixes=("_vhh", "_sabdab")
)

print("Original nanobodies:", len(targets_match))

matched = merged["Hchain"].notna()

print("Matched with SAbDab:", matched.sum())
print("Not matched:", (~matched).sum())

Original nanobodies: 597
Matched with SAbDab: 537
Not matched: 61

# Keep only matched entries with an antigen

In [10]:
with_antigen = merged[
    merged["Hchain"].notna() &
    merged["antigen_chain"].notna() &
    (merged["antigen_chain"].astype(str).str.strip() != "")
].copy()

print("Matched nanobodies:", merged["Hchain"].notna().sum())
print("With antigen:", len(with_antigen))

display(
    with_antigen[
        [
            "pdb_clean",
            "H_clean",
            "antigen_chain",
            "antigen_type",
            "antigen_name",
            "resolution",
            "method"
        ]
    ].head(30)
)

Matched nanobodies: 537
With antigen: 484

KeyError: "['resolution', 'method'] not in index"

# Keep protein antigens

In [11]:
protein_complexes = with_antigen[
    with_antigen["antigen_type"]
    .fillna("")
    .str.lower()
    .eq("protein")
].copy()

print(
    "Nanobody + protein-antigen complexes:",
    len(protein_complexes)
)

Nanobody + protein-antigen complexes: 431

# Check the quality

In [12]:
# See all columns containing resolution
[col for col in protein_complexes.columns if "resolution" in col.lower()]

['resolution_vhh', 'resolution_sabdab']

In [13]:
protein_complexes["resolution_num"] = pd.to_numeric(
    protein_complexes["resolution_sabdab"],
    errors="coerce"
)

print(protein_complexes["resolution_num"].describe())

count    431.000000
mean       2.398569
std        0.684997
min        0.000000
25%        1.990000
50%        2.430000
75%        2.915000
max        3.500000
Name: resolution_num, dtype: float64

In [15]:
display(
    protein_complexes[
        [
            "pdb_clean",
            "H_clean",
            "antigen_chain",
            "antigen_name",
            "resolution_num",
            "method_sabdab"
        ]
    ]
    .sort_values("resolution_num")
    .head(30)
)

,pdb_clean,H_clean,antigen_chain,antigen_name,resolution_num,method_sabdab
275,8CYB,D,A,spike glycoprotein,0.0000,ELECTRON MICROSCOPY
284,8CXN,F,C,spike glycoprotein,0.0000,ELECTRON MICROSCOPY
293,8CYD,F,A,spike glycoprotein,0.0000,ELECTRON MICROSCOPY
234,8GQ5,A,A,nanobody c6,0.0000,ELECTRON MICROSCOPY
220,8CYA,D,C,spike glycoprotein,0.0000,ELECTRON MICROSCOPY
207,8BZY,B,A,solute carrier family 40 member 1,0.0000,ELECTRON MICROSCOPY
219,8CXQ,E,B,spike glycoprotein,0.0000,ELECTRON MICROSCOPY
197,8CY7,F,C,spike glycoprotein,0.0000,ELECTRON MICROSCOPY
265,7WN1,C,A,equilibrative nucleoside/nucleobase transporter,0.0000,ELECTRON MICROSCOPY
269,8DI5,H,C,spike glycoprotein,0.0000,ELECTRON MICROSCOPY
252,8CY6,D,A,spike glycoprotein,0.0000,ELECTRON MICROSCOPY
240,8CYC,D,A,spike glycoprotein,0.0000,ELECTRON MICROSCOPY
113,8QF4,E,A,activity-regulated cytoskeleton-associated pro...,1.0200,X-RAY DIFFRACTION
422,9EZU,B,A,v-set and immunoglobulin domain-containing pro...,1.0500,X-RAY DIFFRACTION
473,9FC2,B,A,spike protein s1,1.2100,X-RAY DIFFRACTION
5,7D5B,D,A,beta-secretase 2,1.3100,X-RAY DIFFRACTION
328,8IM0,B,A,mcherry fluorescent protein,1.3100,X-RAY DIFFRACTION
42,6Z1V,B,A,cd9 antigen,1.3300,X-RAY DIFFRACTION
159,7TGF,B,A,ricin chain a,1.3470,X-RAY DIFFRACTION
189,8EMZ,B,A,gii.17 p domain,1.4000,X-RAY DIFFRACTION
181,7N0R,C,A,nucleoprotein,1.4200,X-RAY DIFFRACTION
408,9M6O,B,A,immunoglobulin g-binding protein a,1.4900,X-RAY DIFFRACTION
383,8WEO,C,B,fragilysin,1.5000,X-RAY DIFFRACTION
450,9ETL,D,A,"2',3'-cyclic-nucleotide 3'-phosphodiesterase",1.5000,X-RAY DIFFRACTION
244,8H63,B,A,internalin a,1.5300,X-RAY DIFFRACTION
448,9IQP,B,A,spike protein s1,1.5500,X-RAY DIFFRACTION
370,8YBO,B,A,enterotoxin type b,1.5900,X-RAY DIFFRACTION
226,8C3L,D,C,phage repressor protein ci,1.5971,X-RAY DIFFRACTION
201,8EN5,G,C,gii.4 p domain,1.6000,X-RAY DIFFRACTION
322,8Q95,C,A,spike protein s1,1.6000,X-RAY DIFFRACTION

# See best candidate complexes

In [16]:
protein_complexes["resolution_num"] = pd.to_numeric(
    protein_complexes["resolution_sabdab"],
    errors="coerce"
)

best = protein_complexes[
    protein_complexes["resolution_num"].notna()
].sort_values("resolution_num")

display(
    best[
        [
            "pdb_clean",
            "H_clean",
            "antigen_chain",
            "antigen_name",
            "antigen_type",
            "resolution_num",
            "method_sabdab"
        ]
    ].head(30)
)
case = best.iloc[0]

print("PDB:", case["pdb_clean"])
print("Nanobody chain:", case["H_clean"])
print("Antigen chain:", case["antigen_chain"])
print("Antigen:", case["antigen_name"])
print("Resolution:", case["resolution_num"])
print("Method:", case["method_sabdab"])

,pdb_clean,H_clean,antigen_chain,antigen_name,antigen_type,resolution_num,method_sabdab
275,8CYB,D,A,spike glycoprotein,protein,0.0000,ELECTRON MICROSCOPY
284,8CXN,F,C,spike glycoprotein,protein,0.0000,ELECTRON MICROSCOPY
293,8CYD,F,A,spike glycoprotein,protein,0.0000,ELECTRON MICROSCOPY
234,8GQ5,A,A,nanobody c6,protein,0.0000,ELECTRON MICROSCOPY
220,8CYA,D,C,spike glycoprotein,protein,0.0000,ELECTRON MICROSCOPY
207,8BZY,B,A,solute carrier family 40 member 1,protein,0.0000,ELECTRON MICROSCOPY
219,8CXQ,E,B,spike glycoprotein,protein,0.0000,ELECTRON MICROSCOPY
197,8CY7,F,C,spike glycoprotein,protein,0.0000,ELECTRON MICROSCOPY
265,7WN1,C,A,equilibrative nucleoside/nucleobase transporter,protein,0.0000,ELECTRON MICROSCOPY
269,8DI5,H,C,spike glycoprotein,protein,0.0000,ELECTRON MICROSCOPY
252,8CY6,D,A,spike glycoprotein,protein,0.0000,ELECTRON MICROSCOPY
240,8CYC,D,A,spike glycoprotein,protein,0.0000,ELECTRON MICROSCOPY
113,8QF4,E,A,activity-regulated cytoskeleton-associated pro...,protein,1.0200,X-RAY DIFFRACTION
422,9EZU,B,A,v-set and immunoglobulin domain-containing pro...,protein,1.0500,X-RAY DIFFRACTION
473,9FC2,B,A,spike protein s1,protein,1.2100,X-RAY DIFFRACTION
5,7D5B,D,A,beta-secretase 2,protein,1.3100,X-RAY DIFFRACTION
328,8IM0,B,A,mcherry fluorescent protein,protein,1.3100,X-RAY DIFFRACTION
42,6Z1V,B,A,cd9 antigen,protein,1.3300,X-RAY DIFFRACTION
159,7TGF,B,A,ricin chain a,protein,1.3470,X-RAY DIFFRACTION
189,8EMZ,B,A,gii.17 p domain,protein,1.4000,X-RAY DIFFRACTION
181,7N0R,C,A,nucleoprotein,protein,1.4200,X-RAY DIFFRACTION
408,9M6O,B,A,immunoglobulin g-binding protein a,protein,1.4900,X-RAY DIFFRACTION
383,8WEO,C,B,fragilysin,protein,1.5000,X-RAY DIFFRACTION
450,9ETL,D,A,"2',3'-cyclic-nucleotide 3'-phosphodiesterase",protein,1.5000,X-RAY DIFFRACTION
244,8H63,B,A,internalin a,protein,1.5300,X-RAY DIFFRACTION
448,9IQP,B,A,spike protein s1,protein,1.5500,X-RAY DIFFRACTION
370,8YBO,B,A,enterotoxin type b,protein,1.5900,X-RAY DIFFRACTION
226,8C3L,D,C,phage repressor protein ci,protein,1.5971,X-RAY DIFFRACTION
201,8EN5,G,C,gii.4 p domain,protein,1.6000,X-RAY DIFFRACTION
322,8Q95,C,A,spike protein s1,protein,1.6000,X-RAY DIFFRACTION

PDB: 8CYB
Nanobody chain: D
Antigen chain: A
Antigen: spike glycoprotein
Resolution: 0.0
Method: ELECTRON MICROSCOPY

# Download the experimental PDB

In [17]:
import requests

pdb_id = case["pdb_clean"].lower()

url = f"https://files.rcsb.org/download/{pdb_id}.pdb"

response = requests.get(url)

if response.status_code == 200:
    pdb_path = f"{pdb_id}.pdb"

    with open(pdb_path, "wb") as f:
        f.write(response.content)

    print("Downloaded:", pdb_path)
else:
    print("Download failed:", response.status_code)

Downloaded: 8cyb.pdb

In [18]:
from Bio.PDB import PDBParser

parser = PDBParser(QUIET=True)
structure = parser.get_structure("complex", pdb_path)

for model in structure:
    print("Model:", model.id)

    for chain in model:
        residues = [
            r for r in chain
            if r.id[0] == " "
        ]

        print(
            "Chain:", chain.id,
            "Residues:", len(residues)
        )

Model: 0
Chain: A Residues: 1102
Chain: B Residues: 1102
Chain: C Residues: 1102
Chain: D Residues: 126
Chain: E Residues: 0
Chain: F Residues: 0
Chain: G Residues: 0
Chain: H Residues: 0
Chain: I Residues: 0
Chain: J Residues: 0
Chain: K Residues: 0
Chain: L Residues: 0
Chain: M Residues: 0
Chain: N Residues: 0
Chain: O Residues: 0
Chain: P Residues: 0
Chain: Q Residues: 0
Chain: R Residues: 0
Chain: S Residues: 0
Chain: T Residues: 0
Chain: U Residues: 0
Chain: V Residues: 0
Chain: W Residues: 0
Chain: X Residues: 0
Chain: Y Residues: 0
Chain: Z Residues: 0

In [ ]:
print("PDB:", case["pdb_clean"])
print("Nanobody chain:", case["H_clean"])
print("Antigen chain(s):", case["antigen_chain"])
print("Antigen type:", case["antigen_type"])
print("Antigen name:", case["antigen_name"])
print("Resolution:", case["resolution_num"])
print("Method:", case["method_sabdab"])

In [ ]:
from Bio.PDB import PDBParser

parser = PDBParser(QUIET=True)
structure = parser.get_structure("complex", pdb_path)

chain_id = case["H_clean"]

chain = structure[0][chain_id]

sequence = ""

from Bio.PDB.Polypeptide import is_aa
from Bio.SeqUtils import seq1

for residue in chain:
    if is_aa(residue, standard=True):
        sequence += seq1(residue.resname)

print("PDB chain:", chain_id)
print("Experimental sequence length:", len(sequence))
print(sequence)

# Sequence from targets_vhh.json
target_row = targets_match[
    (targets_match["pdb_clean"] == case["pdb_clean"]) &
    (targets_match["H_clean"] == case["H_clean"])
].iloc[0]

target_sequence = target_row["hseq"]

print("\nTarget sequence length:", len(target_sequence))
print(target_sequence)

In [ ]:
print(repr(case["antigen_chain"]))
print(case["antigen_name"])

In [ ]:
from Bio.PDB import PDBIO, Select

class ChainSelect(Select):
    def __init__(self, chain_ids):
        self.chain_ids = set(chain_ids)

    def accept_chain(self, chain):
        return chain.id in self.chain_ids


io = PDBIO()
io.set_structure(structure)

# Experimental antigen = chain A
io.save(
    "8CYB_experimental_antigen.pdb",
    ChainSelect(["A"])
)

# Experimental nanobody = chain D
io.save(
    "8CYB_experimental_nanobody.pdb",
    ChainSelect(["D"])
)

print("Created:")
print("  8CYB_experimental_antigen.pdb")
print("  8CYB_experimental_nanobody.pdb")

# Find IgFold prediction

In [ ]:
from pathlib import Path

matches = []

for file in Path("/kaggle/input").rglob("*.pdb"):
    if "8cyb" in file.name.lower() or "8cyb" in str(file).lower():
        matches.append(file)

print("Matches:")
for file in matches:
    print(file)

In [ ]:
from Bio.PDB import PDBParser

igfold_path = "/kaggle/input/datasets/halaragab/igfold-dataset/predictions/8CYBD_igfold.pdb"

parser = PDBParser(QUIET=True)
igfold_structure = parser.get_structure("igfold", igfold_path)

for model in igfold_structure:
    print("Model:", model.id)
    
    for chain in model:
        residues = [
            r for r in chain
            if r.id[0] == " "
        ]
        
        print(
            "Chain:", chain.id,
            "Residues:", len(residues)
        )

In [ ]:
from Bio.PDB import PDBParser, PDBIO, Select

igfold_path = "/kaggle/input/datasets/halaragab/igfold-dataset/predictions/8CYBD_igfold.pdb"

parser = PDBParser(QUIET=True)
igfold_structure = parser.get_structure("igfold", igfold_path)


class RenameChainSelect(Select):
    def accept_chain(self, chain):
        return chain.id == "H"


# Change chain H → B
chain = igfold_structure[0]["H"]
chain.id = "B"

io = PDBIO()
io.set_structure(igfold_structure)
io.save("8CYB_IgFold_nanobody.pdb")

print("Created: 8CYB_IgFold_nanobody.pdb")

In [ ]:
from Bio.PDB import PDBParser
import numpy as np

parser = PDBParser(QUIET=True)
structure = parser.get_structure("8CYB", pdb_path)

antigen = structure[0]["A"]
nanobody = structure[0]["D"]

antigen_atoms = [
    atom for residue in antigen
    if residue.id[0] == " "
    for atom in residue
]

nanobody_atoms = [
    atom for residue in nanobody
    if residue.id[0] == " "
    for atom in residue
]

min_distance = float("inf")

for a in antigen_atoms:
    for b in nanobody_atoms:
        distance = np.linalg.norm(
            a.coord - b.coord
        )

        if distance < min_distance:
            min_distance = distance

print("Minimum antigen–nanobody distance:",
      round(min_distance, 3), "Å")

In [ ]:
from Bio.PDB import PDBParser

def inspect_pdb(path):
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure("structure", path)

    print(f"\n{path}")

    for model in structure:
        for chain in model:
            residues = [
                r for r in chain
                if r.id[0] == " "
            ]

            print(
                f"Chain {chain.id}: "
                f"{len(residues)} residues"
            )

inspect_pdb("8CYB_experimental_antigen.pdb")
inspect_pdb("8CYB_IgFold_nanobody.pdb")

In [ ]:
!pip install -q DockQ

In [ ]:
from pathlib import Path

folder = Path("/kaggle/input/datasets/halaragab/model0")

pdb_files = list(folder.rglob("*.pdb"))

print("PDB files found:", len(pdb_files))

for f in pdb_files:
    print(f)

In [ ]:
from Bio.PDB import PDBParser

parser = PDBParser(QUIET=True)

def check_chains(path):
    structure = parser.get_structure("x", path)

    print("\n", path)

    for model in structure:
        for chain in model:
            residues = [
                r for r in chain
                if r.id[0] == " "
            ]

            if residues:
                print(
                    f"Chain {chain.id}: "
                    f"{len(residues)} residues"
                )

check_chains("/kaggle/input/datasets/halaragab/model0/model_0 (1).pdb")
check_chains("/kaggle/input/datasets/tura76/sabdab-dataset/sabdab_dataset_curated/sabdab_dataset_curated/8cyb/structure/8cyb.pdb")

In [ ]:
from pathlib import Path

pdb_files = list(
    Path("/kaggle/input/datasets/halaragab/model0").rglob("*.pdb")
)

print(pdb_files)
hdock_model = str(pdb_files[0])

native = (
    "/kaggle/input/datasets/tura76/sabdab-dataset/"
    "sabdab_dataset_curated/sabdab_dataset_curated/"
    "8cyb/structure/8cyb.pdb"
)

!DockQ "{hdock_model}" "{native}" --mapping AB:AD

In [22]:
import json

json_path = "/kaggle/input/datasets/potatoguy44/sabdab2-nanobodies/targets_vhh.json"

with open(json_path, "r") as f:
    targets = json.load(f)

print("Type:", type(targets))
print("Number of targets:", len(targets))

# Inspect the first target
print("\nFirst target:")
print(targets[0])

Type: <class 'list'>
Number of targets: 597

First target:
{'instance': 'pdb_000010zo_A_+', 'pdb': '10ZO', 'H': 'A', 'sabdab_id': 'H006BL0000', 'cdrh3_cluster': 'pdb_000010zo_A_+', 'hseq': 'GLVQAGESLRLSCAVPPEVFDIRTVAWYRQVPLGKGRELLSSITPWNKTTYEDSVKDRFTISRDNAKYTVYLQMNDLKPEDTAVYYCAQGWGIASMRYWGQGTQVTVSS', 'numbering': 'IMGT', 'atoms': ['N', 'CA', 'C', 'CB'], 'cdr1': [16, 24], 'cdr2': [42, 49], 'cdr3': [87, 98], 'CDRH1': 'PEVFDIRT', 'CDRH2': 'ITPWNKT', 'CDRH3': 'AQGWGIASMRY', 'resolution': '1.65', 'method': 'XRAY', 'holo': 'True', 'ab_split': 'train', 'PDBdepo': '2026-02-12', 'n_resolved': 109, 'hca': [[[88.824, 104.373, -5.191], [88.668, 103.04, -5.727], [89.946, 102.392, -6.233], None], [[90.696, 103.135, -7.059], [91.981, 102.695, -7.596], [93.088, 103.294, -6.749], [92.164, 103.111, -9.056]], [[93.839, 102.436, -6.076], [94.872, 102.886, -5.169], [96.124, 102.042, -5.386], [94.371, 102.85, -3.714]], [[97.216, 102.501, -4.8], [98.51, 101.857, -4.944], [98.85, 101.089, -3.672], [99.596, 102.898, -5.233]], [[99.654, 100.039, -3.819], [100.069, 99.26, -2.659], [100.732, 100.168, -1.625], [101.023, 98.141, -3.088]], [[100.397, 99.95, -0.348], [100.876, 100.783, 0.733], [100.0, 101.974, 1.054], None], [[98.963, 102.224, 0.266], [98.048, 103.316, 0.54], [96.894, 102.805, 1.399], [97.562, 103.94, -0.764]], [[95.979, 103.706, 1.735], [94.865, 103.398, 2.621], [93.539, 103.724, 1.946], [94.969, 104.174, 3.94]], [[92.491, 103.05, 2.418], [91.118, 103.315, 2.015], [90.221, 103.142, 3.226], [90.638, 102.365, 0.929]], [[89.236, 104.023, 3.354], [88.255, 103.985, 4.428], [86.887, 103.776, 3.798], [88.296, 105.286, 5.232]], [[86.238, 102.663, 4.132], [84.904, 102.383, 3.628], [83.886, 102.65, 4.726], [84.786, 100.936, 3.146]], [[82.703, 103.112, 4.328], [81.678, 103.516, 5.276], [80.372, 102.785, 4.991], [81.451, 105.029, 5.225]], [[79.607, 102.562, 6.06], [78.362, 101.801, 6.007], [77.331, 102.524, 6.864], [78.584, 100.37, 6.497]], [[76.355, 103.164, 6.222], [75.315, 103.861, 6.962], [74.344, 102.857, 7.573], [74.566, 104.833, 6.05]], [[74.044, 103.037, 8.85], [73.092, 102.204, 9.577], [71.955, 103.105, 10.017], [73.734, 101.513, 10.795]], [[70.693, 102.722, 9.814], [69.58, 103.577, 10.24], [69.683, 103.888, 11.722], [68.339, 102.726, 9.93]], [[69.466, 105.146, 12.114], [69.657, 105.517, 13.528], [68.779, 104.731, 14.488], [69.311, 107.013, 13.546]], [[67.596, 104.293, 14.051], [66.702, 103.567, 14.949], [67.289, 102.228, 15.383], [65.344, 103.346, 14.281]], [[68.154, 101.629, 14.564], [68.706, 100.306, 14.822], [70.218, 100.339, 15.018], [68.328, 99.32, 13.697]], [[70.804, 101.53, 15.157], [72.251, 101.619, 15.307], [72.741, 100.934, 16.582], [72.683, 103.078, 15.273]], [[71.918, 100.886, 17.629], [72.277, 100.172, 18.849], [71.68, 98.767, 18.902], [71.861, 100.984, 20.075]], [[71.25, 98.235, 17.755], [70.643, 96.913, 17.661], [71.436, 95.998, 16.732], [69.169, 97.006, 17.203]], [[71.691, 96.445, 15.507], [72.237, 95.55, 14.5], [73.745, 95.379, 14.627], [71.901, 96.059, 13.099]], [[74.196, 94.139, 14.467], [75.593, 93.878, 14.148], [75.862, 94.22, 12.688], [75.924, 92.414, 14.44]], [[77.062, 94.73, 12.421], [77.456, 95.135, 11.077], [78.712, 94.368, 10.686], [77.675, 96.662, 10.992]], [[78.737, 93.875, 9.447], [79.835, 93.056, 8.957], [80.287, 93.525, 7.578], [79.433, 91.571, 8.9]], [[81.592, 93.446, 7.349], [82.19, 93.742, 6.057], [82.575, 92.451, 5.36], [83.42, 94.643, 6.216]], [[82.331, 92.402, 4.048], [82.602, 91.237, 3.23], [83.377, 91.692, 2.008], [81.319, 90.529, 2.753]], [[83.98, 90.731, 1.328], [84.542, 91.059, 0.027], [84.494, 89.847, -0.888], [85.97, 91.594, 0.154]], [[84.354, 90.122, -2.177], [84.34, 89.086, -3.203], [85.589, 89.29, -4.043], [83.08, 89.153, -4.058]], [[86.56, 88.397, -3.878], [87.831, 88.484, -4.591], [87.589, 88.037, -6.029], [88.929, 87.655, -3.899]], [[88.452, 88.413, -6.975], [88.133, 88.189, -8.396], [87.846, 86.739, -8.772], [89.381, 88.725, -9.104]], [[88.51, 85.766, -8.154], [88.297, 84.359, -8.474], [87.611, 83.657, -7.303], [89.623, 83.689, -8.833]], [[86.628, 84.327, -6.708], [86.03, 83.897, -5.454], [84.605, 83.389, -5.642], None], [[84.316, 82.264, -4.996], [82.962, 81.717, -4.916], [82.286, 82.36, -3.709], [83.002, 80.194, -4.808]], [[81.573, 83.453, -3.947], [80.84, 84.137, -2.901], [81.607, 85.26, -2.228], None], [[80.965, 85.809, -1.203], [81.519, 86.904, -0.418], [82.089, 86.352, 0.88], [80.444, 87.954, -0.135]], [[83.327, 86.722, 1.191], [83.999, 86.224, 2.381], [83.9, 87.259, 3.495], [85.465, 85.87, 2.091]], [[83.616, 86.782, 4.704], [83.495, 87.672, 5.844], [84.868, 88.2, 6.228], [82.863, 86.931, 7.02]], [[84.977, 89.519, 6.378], [86.231, 90.155, 6.765], [86.246, 90.574, 8.226], [86.492, 91.389, 5.904]], [[85.158, 91.174, 8.692], [85.135, 91.798, 10.003], [83.685, 92.036, 10.402], [85.921, 93.117, 9.992]], [[83.43, 92.065, 11.707], [82.097, 92.4, 12.188], [82.221, 93.161, 13.498], [81.22, 91.159, 12.383]], [[81.199, 93.955, 13.804], [81.166, 94.727, 15.044], [79.739, 94.745, 15.585], [81.716, 96.154, 14.831]], [[79.589, 94.395, 16.847], [78.294, 94.491, 17.496], [78.092, 95.899, 18.025], [78.207, 93.49, 18.64]], [[76.856, 96.277, 18.356], [76.637, 97.607, 18.938], [77.382, 97.831, 20.254], [75.114, 97.659, 19.13]], [[77.888, 96.775, 20.89], [78.623, 96.853, 22.147], [80.13, 96.748, 21.929], [78.09, 95.772, 23.092]], [[80.555, 96.836, 20.665], [81.948, 96.905, 20.235], [82.707, 95.606, 20.477], [82.68, 98.093, 20.865]], [[82.017, 94.478, 20.357], [82.68, 93.2, 20.157], [83.022, 93.102, 18.677], [81.801, 92.028, 20.576]], [[84.296, 92.899, 18.373], [84.738, 92.836, 16.99], [85.315, 91.462, 16.678], [85.794, 93.9, 16.69]], [[85.237, 91.08, 15.404], [85.902, 89.894, 14.894], [86.646, 90.281, 13.626], [84.916, 88.76, 14.561]], [[87.723, 89.556, 13.336], [88.489, 89.796, 12.122], [88.898, 88.48, 11.492], [89.747, 90.627, 12.389]], [[88.823, 88.425, 10.167], [89.467, 87.349, 9.44], [90.975, 87.478, 9.602], [89.066, 87.388, 7.966]], [[91.635, 86.34, 9.812], [93.03, 86.356, 10.239], [93.949, 86.989, 9.202], [93.486, 84.933, 10.568]], [[93.649, 86.834, 7.917], [94.563, 87.35, 6.904], [94.461, 88.862, 6.712], [94.334, 86.645, 5.561]], [[93.504, 89.537, 7.351], [93.379, 90.987, 7.262], [93.503, 91.675, 8.612], [92.059, 91.404, 6.578]], [[93.664, 90.92, 9.701], [93.586, 91.511, 11.033], [94.683, 92.538, 11.286], [93.643, 90.414, 12.096]], [[95.81, 92.447, 10.597], [96.903, 93.363, 10.873], [96.87, 94.603, 9.989], [98.242, 92.632, 10.74]], [[95.839, 94.764, 9.167], [95.715, 95.976, 8.365], [94.318, 96.578, 8.339], [96.181, 95.705, 6.931]], [[93.278, 95.845, 8.739], [91.896, 96.304, 8.693], [91.376, 96.503, 10.108], [90.979, 95.295, 7.989]], [[90.665, 97.606, 10.331], [90.05, 97.854, 11.63], [88.631, 98.362, 11.425], [90.862, 98.87, 12.447]], [[87.674, 97.773, 12.144], [86.271, 98.166, 12.064], [85.951, 99.044, 13.272], [85.364, 96.911, 11.99]], [[85.086, 100.04, 13.08], [84.7, 100.926, 14.173], [83.327, 101.527, 13.904], [85.711, 102.055, 14.372]], [[82.7, 102.022, 14.973], [81.391, 102.663, 14.916], [81.521, 104.147, 15.229], [80.417, 102.026, 15.915]], [[80.802, 104.976, 14.478], [80.734, 106.412, 14.738], [79.295, 106.741, 15.128], [81.198, 107.237, 13.539]], [[79.074, 106.871, 16.436], [77.748, 107.129, 16.983], [77.123, 108.395, 16.398], [77.841, 107.231, 18.506]], [[77.887, 109.492, 16.334], [77.309, 110.757, 15.877], [76.842, 110.685, 14.431], [78.311, 111.899, 16.027]], [[77.503, 109.877, 13.604], [77.175, 109.793, 12.19], [76.418, 108.525, 11.821], [78.45, 109.906, 11.349]], [[76.111, 107.666, 12.795], [75.361, 106.428, 12.563], [75.98, 105.613, 11.431], [73.889, 106.729, 12.291]], [[77.298, 105.444, 11.51], [78.082, 104.842, 10.445], [79.074, 103.853, 11.041], [78.817, 105.927, 9.64]], [[79.351, 102.789, 10.291], [80.386, 101.815, 10.62], [81.475, 101.931, 9.564], [79.813, 100.386, 10.67]], [[82.717, 102.139, 10.0], [83.845, 102.284, 9.087], [84.688, 101.012, 9.04], [84.733, 103.466, 9.493]], [[85.28, 100.757, 7.875], [86.366, 99.792, 7.749], [87.588, 100.568, 7.276], [86.031, 98.661, 6.777]], [[88.566, 100.737, 8.157], [89.814, 101.393, 7.792], [90.78, 100.333, 7.283], [90.416, 102.141, 8.984]], [[91.178, 100.451, 6.02], [92.133, 99.545, 5.398], [93.456, 100.283, 5.233], [91.596, 99.046, 4.057]], [[94.487, 99.827, 5.939], [95.807, 100.448, 5.878], [96.806, 99.532, 5.179], [96.324, 100.791, 7.284]], [[97.85, 100.128, 4.609], [98.939, 99.37, 3.989], [98.399, 98.342, 2.99], [99.797, 98.689, 5.059]], [[97.622, 98.832, 2.034], [96.897, 97.937, 1.14], [97.854, 97.149, 0.244], [95.896, 98.73, 0.296]], [[97.428, 95.95, -0.134], [98.213, 95.008, -0.917], [97.4, 94.529, -2.11], [98.637, 93.801, -0.068]], [[98.062, 94.06, -3.174], [97.306, 93.599, -4.353], [96.278, 92.536, -4.031], [98.4, 93.057, -5.278]], [[96.521, 91.703, -3.016], [95.55, 90.676, -2.657], [94.27, 91.254, -2.069], [96.171, 89.676, -1.681]], [[94.228, 92.56, -1.795], [93.012, 93.213, -1.325], [92.108, 93.672, -2.458], [93.356, 94.412, -0.441]], [[92.54, 93.536, -3.712], [91.671, 93.842, -4.839], [90.423, 92.973, -4.78], [92.427, 93.608, -6.139]], [[89.255, 93.608, -4.685], [87.996, 92.876, -4.529], [86.837, 93.866, -4.582], [87.944, 92.091, -3.21]], [[85.62, 93.327, -4.553], [84.419, 94.123, -4.335], [84.028, 93.98, -2.875], [83.266, 93.682, -5.249]], [[83.866, 95.107, -2.194], [83.583, 95.13, -0.765], [82.119, 95.47, -0.505], [84.497, 96.137, -0.066]], [[81.5, 94.738, 0.426], [80.1, 94.922, 0.775], [79.937, 95.007, 2.285], [79.235, 93.755, 0.31]], [[78.964, 95.809, 2.712], [78.509, 95.862, 4.095], [77.194, 95.102, 4.224], [78.31, 97.309, 4.562]], [[76.982, 94.488, 5.39], [75.715, 93.837, 5.685], [75.409, 94.064, 7.156], [75.746, 92.331, 5.371]], [[74.126, 93.96, 7.506], [73.661, 94.2, 8.865], [72.636, 93.139, 9.253], [73.028, 95.591, 9.005]], [[72.612, 92.794, 10.535], [71.653, 91.814, 11.01], [71.978, 91.374, 12.424], None], [[71.286, 90.316, 12.855], [71.438, 89.848, 14.225], [72.669, 88.978, 14.415], [70.195, 89.065, 14.668]], [[73.113, 88.305, 13.361], [74.247, 87.404, 13.435], [74.639, 87.022, 12.024], None], [[75.676, 86.188, 11.922], [76.3, 85.93, 10.623], [75.33, 85.23, 9.678], [77.604, 85.125, 10.795]], [[74.54, 84.282, 10.191], [73.613, 83.562, 9.326], [72.414, 84.402, 8.92], [73.118, 82.28, 10.005]], [[72.197, 85.552, 9.558], [71.049, 86.402, 9.26], [71.483, 87.778, 8.767], [70.136, 86.521, 10.489]], [[72.667, 87.86, 8.163], [73.145, 89.106, 7.589], [72.312, 89.455, 6.372], [74.617, 88.996, 7.211]], [[71.741, 90.649, 6.384], [70.938, 91.14, 5.272], [71.2, 92.637, 5.163], [69.462, 90.766, 5.456]], [[70.284, 93.347, 4.511], [70.398, 94.793, 4.348], [71.7, 95.165, 3.645], [70.279, 95.508, 5.696]], [[72.07, 94.37, 2.648], [73.341, 94.558, 1.965], [73.436, 95.935, 1.328], [73.529, 93.477, 0.905]], [[74.582, 96.572, 1.519], [74.855, 97.831, 0.867], [75.411, 97.618, -0.524], None], [[75.576, 98.724, -1.238], [76.143, 98.662, -2.575], [77.603, 98.241, -2.506], [76.013, 100.019, -3.268]], [[78.009, 97.379, -3.434], [79.4, 96.983, -3.498], [80.296, 98.128, -3.931], None], [[81.511, 98.136, -3.382], [82.559, 99.09, -3.731], [83.711, 98.312, -4.342], [83.063, 99.856, -2.501]], [[84.083, 98.657, -5.576], [85.226, 98.024, -6.211], [86.522, 98.688, -5.764], [85.105, 98.112, -7.729]], [[87.478, 97.87, -5.346], [88.783, 98.332, -4.892], [89.832, 97.556, -5.665], [88.967, 98.122, -3.375]], [[90.747, 98.272, -6.319], [91.865, 97.641, -6.993], [93.163, 98.227, -6.465], [91.779, 97.813, -8.51]], [[94.062, 97.34, -6.056], [95.359, 97.69, -5.503], [96.406, 97.423, -6.57], [95.676, 96.874, -4.249]], [[96.966, 98.485, -7.151], [98.023, 98.317, -8.141], [99.35, 98.142, -7.423], [98.085, 99.511, -9.095]], [[100.13, 97.154, -7.851], [101.379, 96.834, -7.164], [102.316, 98.039, -7.146], [102.065, 95.636, -7.823]]]}

In [23]:
print(type(targets))

if isinstance(targets, dict):
    print("Number of entries:", len(targets))
    print("First 3 IDs:", list(targets.keys())[:3])

<class 'list'>

In [24]:
if isinstance(targets[0], dict):
    print("\nKeys in first target:")
    print(targets[0].keys())

Keys in first target:
dict_keys(['instance', 'pdb', 'H', 'sabdab_id', 'cdrh3_cluster', 'hseq', 'numbering', 'atoms', 'cdr1', 'cdr2', 'cdr3', 'CDRH1', 'CDRH2', 'CDRH3', 'resolution', 'method', 'holo', 'ab_split', 'PDBdepo', 'n_resolved', 'hca'])

In [25]:
import pandas as pd

# Convert the JSON list into a dataframe
targets_df = pd.DataFrame(targets)

print("Shape:", targets_df.shape)
display(targets_df[[
    "pdb",
    "H",
    "instance",
    "holo",
    "sabdab_id"
]].head(10))

Shape: (597, 21)

    pdb  H          instance   holo   sabdab_id
0  10ZO  A  pdb_000010zo_A_+   True  H006BL0000
1  8F0K  N  pdb_00008f0k_N_+   True  H0098L0000
2  7R73  A  pdb_00007r73_A_+   True  H00EZL0000
3  7RG7  A  pdb_00007rg7_A_+   True  H00H1L0000
4  9UAQ  F  pdb_00009uaq_F_+   True  H05MGL0000
5  7D5B  D  pdb_00007d5b_D_+   True  H00QEL0000
6  7L6V  E  pdb_00007l6v_E_+   True  H00RWL0000
7  7XKA  B  pdb_00007xka_B_+  False  H00WRL0000
8  7ZQT  F  pdb_00007zqt_F_+   True  H013QL0000
9  7A5V  O  pdb_00007a5v_O_+   True  H029SL0000

In [26]:
print(targets_df["holo"].value_counts(dropna=False))
print("Total VHHs:", len(targets_df))
print("Holo VHHs:", targets_df["holo"].sum())

holo
True     575
False     22
Name: count, dtype: int64
Total VHHs: 597
Holo VHHs: TrueTrueTrueTrueTrueTrueTrueFalseTrueTrueTrueTrueTrueTrueTrueFalseTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueFalseTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueFalseFalseFalseTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueFalseTrueTrueTrueTrueTrueFalseFalseTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueFalseTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueFalseFalseTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueFalseTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueFalseTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueFalseTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueFalseTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueFalseTrueTrueTrueFalseTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueFalseTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueFalseTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueFalseTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueTrueFalseTrueTrueTrueTrue

In [42]:
# Convert holo to actual Boolean
targets_df["holo_bool"] = (
    targets_df["holo"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("true")
)

# Keep only holo VHHs
holo_targets = targets_df[targets_df["holo_bool"]].copy()

print("Total VHHs:", len(targets_df))
print("Holo VHHs:", len(holo_targets))
print("Non-holo VHHs:", len(targets_df) - len(holo_targets))

Total VHHs: 597
Holo VHHs: 575
Non-holo VHHs: 22

In [27]:
holo_targets[
    holo_targets["pdb"].astype(str).str.upper() == "7R73"
][
    ["pdb", "H", "instance", "sabdab_id", "holo"]
]

    pdb  H          instance   sabdab_id  holo
2  7R73  A  pdb_00007r73_A_+  H00EZL0000  True

In [28]:
print(targets_df.shape)
print(targets_df.columns.tolist())

(597, 21)
['instance', 'pdb', 'H', 'sabdab_id', 'cdrh3_cluster', 'hseq', 'numbering', 'atoms', 'cdr1', 'cdr2', 'cdr3', 'CDRH1', 'CDRH2', 'CDRH3', 'resolution', 'method', 'holo', 'ab_split', 'PDBdepo', 'n_resolved', 'hca']

In [29]:
print(df_sabdab.columns.tolist())

['pdb', 'Hchain', 'Lchain', 'antigen_chain', 'antigen_type', 'antigen_name', 'resolution', 'method']

In [30]:
df_sabdab[
    df_sabdab["pdb"].astype(str).str.upper() == "7R73"
]

,pdb,Hchain,Lchain,antigen_chain,antigen_type,antigen_name,resolution,method
11608,7r73,A,NaN,G,protein,glycoprotein 120,1.76,X-RAY DIFFRACTION

# build the complete docking-target table

In [31]:
# Keep only the SAbDab columns we need
sabdab_mapping = df_sabdab[
    ["pdb", "Hchain", "antigen_chain", "antigen_type", "antigen_name"]
].copy()

# Normalize PDB and chain values
sabdab_mapping["pdb"] = (
    sabdab_mapping["pdb"]
    .astype(str)
    .str.upper()
    .str.strip()
)

sabdab_mapping["Hchain"] = (
    sabdab_mapping["Hchain"]
    .astype(str)
    .str.strip()
)

# Normalize the VHH dataframe
holo_targets["pdb"] = (
    holo_targets["pdb"]
    .astype(str)
    .str.upper()
    .str.strip()
)

holo_targets["H"] = (
    holo_targets["H"]
    .astype(str)
    .str.strip()
)

# Merge VHHs with their antigen information
docking_targets = holo_targets.merge(
    sabdab_mapping,
    left_on=["pdb", "H"],
    right_on=["pdb", "Hchain"],
    how="inner"
)

print("Docking targets:", len(docking_targets))

display(
    docking_targets[
        [
            "pdb",
            "H",
            "antigen_chain",
            "antigen_type",
            "antigen_name",
            "sabdab_id"
        ]
    ].head(20)
)

Docking targets: 515

,pdb,H,antigen_chain,antigen_type,antigen_name,sabdab_id
0,8F0K,N,A | G | B,protein | protein | protein,guanine nucleotide-binding protein g(s) subuni...,H0098L0000
1,7R73,A,G,protein,glycoprotein 120,H00EZL0000
2,7RG7,A,A,Hapten,METHOTREXATE,H00H1L0000
3,9UAQ,F,I | C,protein | protein,"green fluorescent protein | h3-prac-5350a,2-de...",H05MGL0000
4,7D5B,D,A,protein,beta-secretase 2,H00QEL0000
5,7L6V,E,A,protein,bont/a,H00RWL0000
6,7ZQT,F,E,protein,adhesin binding fucosylated histo-blood group ...,H013QL0000
7,7A5V,O,A,protein,gamma-aminobutyric acid receptor subunit beta-...,H029SL0000
8,8W1V,F,B,protein,"beta-2 adrenergic receptor,endolysin",H01G2L0000
9,9FAK,G,A | E,protein | protein,gamma-aminobutyric acid receptor subunit alpha...,H01PPL0000
10,7AQG,C,A,protein,plasminogen activator inhibitor 1,H01Q4L0000
11,9UYN,B,A | R,protein | protein,"beta-arrestin-1 | chemerin-like receptor 2,vas...",H0224L0000
12,8YA0,V,Y | E,protein | protein,protein translocase subunit secy | protein tra...,H024PL0000
13,8TAO,D,A,protein,metabotropic glutamate receptor 5,H0250L0000
14,9LR1,C,R,protein,apelin receptor,H04WXL0000
15,7SAJ,F,E,protein,mcherry,H025TL0000
16,8APY,C,A,protein,er lumen protein-retaining receptor 2,H026PL0000
17,8UY6,D,C,protein,aquaporin z,H0287L0000
18,9B71,G,A,protein,phospho-n-acetylmuramoyl-pentapeptide-transferase,H028ZL0000
19,7M1H,D,A,protein,botulinum neurotoxin a light chain,H02AWL0000

In [32]:
docking_targets[
    docking_targets["pdb"] == "7R73"
][
    [
        "pdb",
        "H",
        "antigen_chain",
        "antigen_type",
        "antigen_name",
        "sabdab_id"
    ]
]

    pdb  H antigen_chain antigen_type      antigen_name   sabdab_id
1  7R73  A             G      protein  glycoprotein 120  H00EZL0000

In [33]:
print(
    docking_targets[
        ["pdb", "H", "antigen_chain"]
    ].duplicated().sum()
)

0

In [34]:
print(
    docking_targets.groupby(["pdb", "H"]).size()
    .sort_values(ascending=False)
    .head(10)
)

pdb   H
9Z5Q  A    1
6X04  J    1
6X05  K    1
9MNZ  C    1
9MTE  A    1
      B    1
9MTX  A    1
9MVU  D    1
9MW5  E    1
9MY8  A    1
dtype: int64

In [35]:
import json

with open("/kaggle/input/datasets/halaragab/simple-fold-results/results_vhh.json", "r") as f:
    simplefold_results = json.load(f)

print(type(simplefold_results))

if isinstance(simplefold_results, dict):
    print(simplefold_results.keys())
else:
    print("Number of entries:", len(simplefold_results))

print("\nFirst entry:")
print(
    simplefold_results[0]
    if isinstance(simplefold_results, list)
    else next(iter(simplefold_results.items()))
)

<class 'dict'>
dict_keys(['model', 'settings', 'metric', 'reference_only', 'gpus', 'elapsed_min', 'stage', 'work_free_gb', 'tmp_free_gb', 'patch', 'n_targets', 'warm_rc', 'shard_sizes', 'fold_rc', 'fold_sec', 'n_predicted', 'sec_per_target', 'rows', 'summary'])

First entry:
('model', 'simplefold_100M')

In [36]:
print(type(simplefold_results["rows"]))
print("Number of rows:", len(simplefold_results["rows"]))

print("\nFirst row:")
print(simplefold_results["rows"][0])

<class 'list'>
Number of rows: 597

First row:
{'instance': 'pdb_000010zo_A_+', 'tid': '10ZOA', 'L': 109, 'cdr3_len': 11, 'n_atoms_matched': 428, 'method': 'XRAY', 'holo': 'True', 'ab_split': 'train', 'resolution': '1.65', 'chain_cdr1': 1.425, 'chain_cdr2': 0.59, 'chain_cdr3': 1.083, 'chain_framework': 1.048, 'fw_cdr1': 1.628, 'fw_cdr2': 0.649, 'fw_cdr3': 1.136, 'fw_framework': 1.031}

In [37]:
if isinstance(simplefold_results["rows"][0], dict):
    print("\nRow keys:")
    print(simplefold_results["rows"][0].keys())

Row keys:
dict_keys(['instance', 'tid', 'L', 'cdr3_len', 'n_atoms_matched', 'method', 'holo', 'ab_split', 'resolution', 'chain_cdr1', 'chain_cdr2', 'chain_cdr3', 'chain_framework', 'fw_cdr1', 'fw_cdr2', 'fw_cdr3', 'fw_framework'])

In [38]:
row0 = simplefold_results["rows"][0]

for key, value in row0.items():
    print(f"{key}: {value}")
print("First 10 SimpleFold tids:")

for row in simplefold_results["rows"][:10]:
    print(row["tid"])

instance: pdb_000010zo_A_+
tid: 10ZOA
L: 109
cdr3_len: 11
n_atoms_matched: 428
method: XRAY
holo: True
ab_split: train
resolution: 1.65
chain_cdr1: 1.425
chain_cdr2: 0.59
chain_cdr3: 1.083
chain_framework: 1.048
fw_cdr1: 1.628
fw_cdr2: 0.649
fw_cdr3: 1.136
fw_framework: 1.031
First 10 SimpleFold tids:
10ZOA
8F0KN
7R73A
7RG7A
9UAQF
7D5BD
7L6VE
7XKAB
7ZQTF
7A5VO

In [39]:
print("\nFirst 10 targets:")

for target in targets[:10]:
    print(
        target["pdb"],
        target["H"],
        target["instance"],
        target["sabdab_id"]
    )

First 10 targets:
10ZO A pdb_000010zo_A_+ H006BL0000
8F0K N pdb_00008f0k_N_+ H0098L0000
7R73 A pdb_00007r73_A_+ H00EZL0000
7RG7 A pdb_00007rg7_A_+ H00H1L0000
9UAQ F pdb_00009uaq_F_+ H05MGL0000
7D5B D pdb_00007d5b_D_+ H00QEL0000
7L6V E pdb_00007l6v_E_+ H00RWL0000
7XKA B pdb_00007xka_B_+ H00WRL0000
7ZQT F pdb_00007zqt_F_+ H013QL0000
7A5V O pdb_00007a5v_O_+ H029SL0000

In [ ]:
print("Settings:")
for k, v in simplefold_results["settings"].items():
    print(k, ":", v)

In [40]:
print("\nSummary:")
print(simplefold_results["summary"])

Summary:
{'n': 597, 'chain_aligned': {'cdr1': {'median': 1.955, 'mean': 2.186, 'ci95': [1.826, 2.066], 'n': 597}, 'cdr2': {'median': 1.241, 'mean': 1.509, 'ci95': [1.134, 1.317], 'n': 597}, 'cdr3': {'median': 2.942, 'mean': 3.602, 'ci95': [2.774, 3.155], 'n': 597}, 'framework': {'median': 0.826, 'mean': 0.989, 'ci95': [0.788, 0.853], 'n': 597}}, 'fw_aligned': {'cdr1': {'median': 1.916, 'mean': 2.213, 'ci95': [1.775, 2.046], 'n': 597}, 'cdr2': {'median': 1.056, 'mean': 1.38, 'ci95': [0.996, 1.108], 'n': 597}, 'cdr3': {'median': 3.194, 'mean': 4.04, 'ci95': [2.954, 3.429], 'n': 597}, 'framework': {'median': 0.677, 'mean': 0.822, 'ci95': [0.655, 0.693], 'n': 597}}, 'strata': {'ab_split==test': {'n': 148, 'chain_aligned': {'cdr1': {'median': 2.161, 'mean': 2.273, 'ci95': [1.826, 2.354], 'n': 148}, 'cdr2': {'median': 1.147, 'mean': 1.437, 'ci95': [1.0, 1.309], 'n': 148}, 'cdr3': {'median': 2.953, 'mean': 3.649, 'ci95': [2.446, 3.416], 'n': 148}, 'framework': {'median': 0.841, 'mean': 0.975, 'ci95': [0.763, 0.939], 'n': 148}}, 'fw_aligned': {'cdr1': {'median': 1.969, 'mean': 2.284, 'ci95': [1.686, 2.316], 'n': 148}, 'cdr2': {'median': 1.0, 'mean': 1.277, 'ci95': [0.893, 1.101], 'n': 148}, 'cdr3': {'median': 3.381, 'mean': 4.091, 'ci95': [2.653, 3.661], 'n': 148}, 'framework': {'median': 0.677, 'mean': 0.804, 'ci95': [0.624, 0.743], 'n': 148}}}, 'method==XRAY': {'n': 408, 'chain_aligned': {'cdr1': {'median': 1.872, 'mean': 2.134, 'ci95': [1.729, 2.043], 'n': 408}, 'cdr2': {'median': 1.204, 'mean': 1.488, 'ci95': [1.093, 1.32], 'n': 408}, 'cdr3': {'median': 2.908, 'mean': 3.529, 'ci95': [2.656, 3.079], 'n': 408}, 'framework': {'median': 0.766, 'mean': 0.927, 'ci95': [0.734, 0.807], 'n': 408}}, 'fw_aligned': {'cdr1': {'median': 1.889, 'mean': 2.16, 'ci95': [1.748, 2.045], 'n': 408}, 'cdr2': {'median': 1.041, 'mean': 1.376, 'ci95': [0.96, 1.125], 'n': 408}, 'cdr3': {'median': 3.077, 'mean': 3.951, 'ci95': [2.869, 3.363], 'n': 408}, 'framework': {'median': 0.627, 'mean': 0.761, 'ci95': [0.601, 0.651], 'n': 408}}}, 'method==EM': {'n': 189, 'chain_aligned': {'cdr1': {'median': 2.073, 'mean': 2.299, 'ci95': [1.829, 2.431], 'n': 189}, 'cdr2': {'median': 1.256, 'mean': 1.556, 'ci95': [1.128, 1.542], 'n': 189}, 'cdr3': {'median': 3.132, 'mean': 3.759, 'ci95': [2.652, 3.451], 'n': 189}, 'framework': {'median': 0.964, 'mean': 1.121, 'ci95': [0.883, 1.044], 'n': 189}}, 'fw_aligned': {'cdr1': {'median': 1.939, 'mean': 2.328, 'ci95': [1.738, 2.423], 'n': 189}, 'cdr2': {'median': 1.082, 'mean': 1.388, 'ci95': [1.004, 1.22], 'n': 189}, 'cdr3': {'median': 3.35, 'mean': 4.232, 'ci95': [2.934, 3.825], 'n': 189}, 'framework': {'median': 0.789, 'mean': 0.953, 'ci95': [0.742, 0.84], 'n': 189}}}, 'holo==True': {'n': 575, 'chain_aligned': {'cdr1': {'median': 1.946, 'mean': 2.179, 'ci95': [1.82, 2.065], 'n': 575}, 'cdr2': {'median': 1.216, 'mean': 1.508, 'ci95': [1.124, 1.312], 'n': 575}, 'cdr3': {'median': 2.905, 'mean': 3.59, 'ci95': [2.698, 3.132], 'n': 575}, 'framework': {'median': 0.828, 'mean': 0.992, 'ci95': [0.788, 0.853], 'n': 575}}, 'fw_aligned': {'cdr1': {'median': 1.915, 'mean': 2.208, 'ci95': [1.759, 2.046], 'n': 575}, 'cdr2': {'median': 1.056, 'mean': 1.38, 'ci95': [0.996, 1.124], 'n': 575}, 'cdr3': {'median': 3.138, 'mean': 4.028, 'ci95': [2.929, 3.418], 'n': 575}, 'framework': {'median': 0.678, 'mean': 0.825, 'ci95': [0.657, 0.695], 'n': 575}}}, 'holo==False': {'n': 22, 'chain_aligned': {'cdr1': {'median': 2.309, 'mean': 2.386, 'ci95': [1.365, 3.036], 'n': 22}, 'cdr2': {'median': 1.433, 'mean': 1.549, 'ci95': [1.111, 1.786], 'n': 22}, 'cdr3': {'median': 3.426, 'mean': 3.908, 'ci95': [2.974, 4.066], 'n': 22}, 'framework': {'median': 0.786, 'mean': 0.909, 'ci95': [0.698, 0.96], 'n': 22}}, 'fw_aligned': {'cdr1': {'median': 2.082, 'mean': 2.359, 'ci95': [1.219, 3.02], 'n': 22}, 'cdr2': {'median': 1.076, 'mean': 1.387, 'ci95': [0.811, 1.588], 'n': 22}, 'cdr3': {'median': 3.806, 'mean': 4.352, 'ci95': [3.095, 4.665], 'n': 22}, 'framework': {'median': 0.643, 'mean': 0.743, 'ci95': [0.518, 0.888], 'n': 22}}}, 'cdr3_len 0-13': {'n': 195, 'chain_aligned': {'cdr1': {'median': 1.828, 'mean': 2.078, 'ci95': [1.628, 2.121], 'n': 195}, 'cdr2': {'median': 1.064, 'mean': 1.372, 'ci95': [0.996, 1.213], 'n': 195}, 'cdr3': {'median': 2.414, 'mean': 2.849, 'ci95': [2.054, 2.673], 'n': 195}, 'framework': {'median': 0.786, 'mean': 0.936, 'ci95': [0.747, 0.846], 'n': 195}}, 'fw_aligned': {'cdr1': {'median': 1.93, 'mean': 2.186, 'ci95': [1.738, 2.231], 'n': 195}, 'cdr2': {'median': 1.06, 'mean': 1.392, 'ci95': [0.988, 1.146], 'n': 195}, 'cdr3': {'median': 2.618, 'mean': 3.138, 'ci95': [2.339, 2.974], 'n': 195}, 'framework': {'median': 0.7, 'mean': 0.856, 'ci95': [0.67, 0.747], 'n': 195}}}, 'cdr3_len 14-17': {'n': 188, 'chain_aligned': {'cdr1': {'median': 2.079, 'mean': 2.389, 'ci95': [1.906, 2.293], 'n': 188}, 'cdr2': {'median': 1.463, 'mean': 1.657, 'ci95': [1.246, 1.648], 'n': 188}, 'cdr3': {'median': 3.369, 'mean': 4.243, 'ci95': [2.958, 3.824], 'n': 188}, 'framework': {'median': 0.887, 'mean': 1.096, 'ci95': [0.828, 0.949], 'n': 188}}, 'fw_aligned': {'cdr1': {'median': 1.961, 'mean': 2.382, 'ci95': [1.772, 2.32], 'n': 188}, 'cdr2': {'median': 1.081, 'mean': 1.432, 'ci95': [0.919, 1.178], 'n': 188}, 'cdr3': {'median': 3.75, 'mean': 4.849, 'ci95': [3.201, 4.29], 'n': 188}, 'framework': {'median': 0.663, 'mean': 0.87, 'ci95': [0.629, 0.72], 'n': 188}}}, 'cdr3_len 18-99': {'n': 214, 'chain_aligned': {'cdr1': {'median': 1.882, 'mean': 2.107, 'ci95': [1.728, 2.084], 'n': 214}, 'cdr2': {'median': 1.248, 'mean': 1.505, 'ci95': [1.114, 1.38], 'n': 214}, 'cdr3': {'median': 3.006, 'mean': 3.724, 'ci95': [2.78, 3.381], 'n': 214}, 'framework': {'median': 0.811, 'mean': 0.942, 'ci95': [0.755, 0.868], 'n': 214}}, 'fw_aligned': {'cdr1': {'median': 1.817, 'mean': 2.09, 'ci95': [1.669, 2.069], 'n': 214}, 'cdr2': {'median': 1.034, 'mean': 1.325, 'ci95': [0.954, 1.144], 'n': 214}, 'cdr3': {'median': 3.306, 'mean': 4.151, 'ci95': [2.986, 3.668], 'n': 214}, 'framework': {'median': 0.647, 'mean': 0.749, 'ci95': [0.613, 0.684], 'n': 214}}}}, 'cdr3_err_vs_len_spearman': 0.19, 'reference_NanoBodyBuilder2': {'NanoBodyBuilder2': {'cdr1': 1.98, 'cdr2': 1.37, 'cdr3': 2.89, 'framework': 0.79}, 'AlphaFold2_cdr3': 3.44, 'caveat': 'ImmuneBuilder Tab.3 -- DIFFERENT test set, not paired'}}

In [43]:
sabdab_mapping = df_sabdab[
    ["pdb", "Hchain", "antigen_chain", "antigen_type", "antigen_name"]
].copy()

sabdab_mapping["pdb"] = (
    sabdab_mapping["pdb"]
    .astype(str)
    .str.upper()
    .str.strip()
)

sabdab_mapping["Hchain"] = (
    sabdab_mapping["Hchain"]
    .astype(str)
    .str.strip()
)

holo_targets = targets_df[
    targets_df["holo_bool"] == True
].copy()

holo_targets["pdb"] = (
    holo_targets["pdb"]
    .astype(str)
    .str.upper()
    .str.strip()
)

holo_targets["H"] = (
    holo_targets["H"]
    .astype(str)
    .str.strip()
)

In [44]:
docking_targets = holo_targets.merge(
    sabdab_mapping,
    left_on=["pdb", "H"],
    right_on=["pdb", "Hchain"],
    how="inner"
)

print("Holo VHHs:", len(holo_targets))
print("Targets with antigen mapping:", len(docking_targets))

display(
    docking_targets[
        ["pdb", "H", "antigen_chain",
         "antigen_name", "sabdab_id"]
    ].head(20)
)

Holo VHHs: 575
Targets with antigen mapping: 515

,pdb,H,antigen_chain,antigen_name,sabdab_id
0,8F0K,N,A | G | B,guanine nucleotide-binding protein g(s) subuni...,H0098L0000
1,7R73,A,G,glycoprotein 120,H00EZL0000
2,7RG7,A,A,METHOTREXATE,H00H1L0000
3,9UAQ,F,I | C,"green fluorescent protein | h3-prac-5350a,2-de...",H05MGL0000
4,7D5B,D,A,beta-secretase 2,H00QEL0000
5,7L6V,E,A,bont/a,H00RWL0000
6,7ZQT,F,E,adhesin binding fucosylated histo-blood group ...,H013QL0000
7,7A5V,O,A,gamma-aminobutyric acid receptor subunit beta-...,H029SL0000
8,8W1V,F,B,"beta-2 adrenergic receptor,endolysin",H01G2L0000
9,9FAK,G,A | E,gamma-aminobutyric acid receptor subunit alpha...,H01PPL0000
10,7AQG,C,A,plasminogen activator inhibitor 1,H01Q4L0000
11,9UYN,B,A | R,"beta-arrestin-1 | chemerin-like receptor 2,vas...",H0224L0000
12,8YA0,V,Y | E,protein translocase subunit secy | protein tra...,H024PL0000
13,8TAO,D,A,metabotropic glutamate receptor 5,H0250L0000
14,9LR1,C,R,apelin receptor,H04WXL0000
15,7SAJ,F,E,mcherry,H025TL0000
16,8APY,C,A,er lumen protein-retaining receptor 2,H026PL0000
17,8UY6,D,C,aquaporin z,H0287L0000
18,9B71,G,A,phospho-n-acetylmuramoyl-pentapeptide-transferase,H028ZL0000
19,7M1H,D,A,botulinum neurotoxin a light chain,H02AWL0000

In [45]:
import os

# Example — CHANGE these to your actual folders
simplefold_dir = "/kaggle/input/datasets/halaragab/simplefold-target"
igfold_dir = "/kaggle/input/datasets/halaragab/igfold-dataset/predictions"
nbb2_dir = "/kaggle/input/datasets/halaragab/nbb2results"

target_id = "7R73A"

for directory in [simplefold_dir, igfold_dir, nbb2_dir]:

    print("\n", directory)

    if os.path.exists(directory):
        matches = [
            f for f in os.listdir(directory)
            if target_id.lower() in f.lower()
        ]

        print(matches[:10])

 /kaggle/input/datasets/halaragab/simplefold-target
[]

 /kaggle/input/datasets/halaragab/igfold-dataset/predictions
['7R73A_igfold.fasta', '7R73A_igfold.pdb']

 /kaggle/input/datasets/halaragab/nbb2results
[]

In [46]:
import os

paths = [
    "/kaggle/input/datasets/halaragab/simplefold-target",
    "/kaggle/input/datasets/halaragab/nbb2results"
]

for path in paths:
    print("\n====================")
    print(path)

    for root, dirs, files in os.walk(path):
        print("ROOT:", root)
        print("FILES:", files[:20])

====================
/kaggle/input/datasets/halaragab/simplefold-target
ROOT: /kaggle/input/datasets/halaragab/simplefold-target
FILES: ['per_target_scores.json']

====================
/kaggle/input/datasets/halaragab/nbb2results
ROOT: /kaggle/input/datasets/halaragab/nbb2results
FILES: ['results_nbb2.json']

In [47]:
import json

simplefold_path = "/kaggle/input/datasets/halaragab/simplefold-target/per_target_scores.json"

with open(simplefold_path, "r") as f:
    sf = json.load(f)

print(type(sf))
print(sf.keys() if isinstance(sf, dict) else len(sf))

<class 'list'>
597

In [48]:
print("First row:")
print(sf["rows"][0] if "rows" in sf else sf[0])

First row:
{'instance': 'pdb_000010zo_A_+', 'tid': '10ZOA', 'L': 109, 'cdr3_len': 11, 'n_atoms_matched': 428, 'method': 'XRAY', 'holo': 'True', 'ab_split': 'train', 'resolution': '1.65', 'chain_cdr1': 1.425, 'chain_cdr2': 0.59, 'chain_cdr3': 1.083, 'chain_framework': 1.048, 'fw_cdr1': 1.628, 'fw_cdr2': 0.649, 'fw_cdr3': 1.136, 'fw_framework': 1.031}

In [49]:
nbb2_path = "/kaggle/input/datasets/halaragab/nbb2-target/per_target_scores_nbb2.json"

with open(nbb2_path, "r") as f:
    nbb2 = json.load(f)

print(type(nbb2))
print(nbb2.keys() if isinstance(nbb2, dict) else len(nbb2))

print(
    nbb2["rows"][0]
    if isinstance(nbb2, dict) and "rows" in nbb2
    else nbb2[0]
)

<class 'list'>
588
{'instance': 'pdb_00008f0k_N_+', 'tid': '8F0KN', 'L': 128, 'cdr3_len': 21, 'n_atoms_matched': 499, 'seq_offset': 0, 'pred_len': 128, 'method': 'EM', 'holo': 'True', 'ab_split': 'train', 'resolution': '1.9', 'chain_cdr1': 0.175, 'chain_cdr2': 0.221, 'chain_cdr3': 0.537, 'chain_framework': 0.355, 'fw_cdr1': 0.182, 'fw_cdr2': 0.218, 'fw_cdr3': 0.567, 'fw_framework': 0.351}

In [50]:
!pip install -q pdbfixer openmm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 665.9/665.9 kB 10.5 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.4/14.4 MB 96.7 MB/s eta 0:00:00:00:0100:01
  Building wheel for pdbfixer (setup.py) ... done

In [57]:
!pip install -q ImmuneBuilder

In [58]:
from ImmuneBuilder import NanoBodyBuilder2

print("NBB2 imported successfully!")

NBB2 imported successfully!

In [55]:
!pip install -q git+https://github.com/cmoscy/ANARCI-pyhmmr.git

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done

In [60]:
import json
from ImmuneBuilder import NanoBodyBuilder2

# Load dataset
with open(
    "/kaggle/input/datasets/potatoguy44/sabdab2-nanobodies/targets_vhh.json",
    "r"
) as f:
    targets = json.load(f)

# First target
target = targets[0]

tid = target["pdb"].upper() + target["H"]
sequence = target["hseq"]

print("Target:", tid)
print("Length:", len(sequence))

# Create predictor
predictor = NanoBodyBuilder2()

# Predict
prediction = predictor.predict({"H": sequence})

print("Prediction successful")
print("Atoms type:", type(prediction.atoms))

try:
    print("Atoms shape:", prediction.atoms.shape)
except:
    print("Atoms has no shape attribute")

print(prediction.atoms)

Target: 10ZOA
Length: 109

AssertionError: Sequence missing too many residues to model correctly. Please give whole sequence:
GLVQAGESLRLSCAVPPEVFDIRTVAWYRQVPLGKGRELLSSITPWNKTTYEDSVKDRFTISRDNAKYTVYLQMNDLKPEDTAVYYCAQGWGIASMRYWGQGTQVTVSS

In [61]:
# Find 7R73A explicitly

target = next(
    t for t in targets
    if t["pdb"].upper() == "7R73" and t["H"].upper() == "A"
)

print("PDB:", target["pdb"])
print("Chain:", target["H"])
print("Instance:", target["instance"])
print("Sequence length:", len(target["hseq"]))
print("Sequence:")
print(target["hseq"])

PDB: 7R73
Chain: A
Instance: pdb_00007r73_A_+
Sequence length: 126
Sequence:
VQLQESGGGLVQAGGSLRLSCTVSARTSSSHDMGWFRQAPGKEREFVAAISWSGGTTNYVDSVKGRFDISKDNAKNAVYLQMNSLKPEDTAVYYCAAKWRPLRYSDNPSNSDYNYWGQGTQVTVSS

In [62]:
sequence = target["hseq"]

prediction = predictor.predict({"H": sequence})

print("SUCCESS")
print("Prediction type:", type(prediction))
print("Attributes:", prediction.__dict__.keys())

SUCCESS
Prediction type: <class 'ImmuneBuilder.NanoBodyBuilder2.Nanobody'>
Attributes: dict_keys(['numbered_sequences', 'atoms', 'encodings', 'R', 't', 'aligned_traces', 'error_estimates', 'ranking'])

In [63]:
atoms = prediction.atoms

print("Type:", type(atoms))

try:
    print("Shape:", atoms.shape)
except Exception as e:
    print("No shape:", e)

print("\nFirst element:")
try:
    print(atoms[0])
except Exception as e:
    print("Cannot index [0]:", e)

Type: <class 'list'>
No shape: 'list' object has no attribute 'shape'

First element:
tensor([[[ -9.0446,  -4.0631, -12.2410],
         [ -9.2580,  -5.2525, -13.0590],
         [ -7.5753,  -3.6518, -12.3001],
         ...,
         [     nan,      nan,      nan],
         [     nan,      nan,      nan],
         [     nan,      nan,      nan]],

        [[ -6.4747,  -1.8966, -12.1473],
         [ -7.8262,  -2.4128, -11.9571],
         [ -6.1105,  -0.8934, -11.0566],
         ...,
         [     nan,      nan,      nan],
         [     nan,      nan,      nan],
         [     nan,      nan,      nan]],

        [[ -4.3783,  -0.2919,  -9.6539],
         [ -4.8828,  -1.1528, -10.7181],
         [ -3.1900,   0.5319, -10.1385],
         ...,
         [     nan,      nan,      nan],
         [     nan,      nan,      nan],
         [     nan,      nan,      nan]],

        ...,

        [[ 14.5717,   7.8193,   2.3956],
         [ 14.3425,   6.9977,   1.2117],
         [ 16.0719,   7.9873,   2.6258],
         ...,
         [     nan,      nan,      nan],
         [     nan,      nan,      nan],
         [     nan,      nan,      nan]],

        [[ 17.7504,   9.5671,   2.9408],
         [ 16.3398,   9.2610,   2.7264],
         [ 18.0346,   9.8644,   4.4093],
         ...,
         [     nan,      nan,      nan],
         [     nan,      nan,      nan],
         [     nan,      nan,      nan]],

        [[ 19.4880,   9.5206,   6.3576],
         [ 19.0729,   9.3262,   4.9722],
         [ 19.9732,  10.9469,   6.5944],
         ...,
         [     nan,      nan,      nan],
         [     nan,      nan,      nan],
         [     nan,      nan,      nan]]], device='cuda:0')

In [64]:
from ImmuneBuilder.util import to_pdb
import inspect

print(inspect.signature(to_pdb))
print(inspect.getsource(to_pdb))

(numbered_sequences, all_atoms, chain_ids='HL')
def to_pdb(numbered_sequences, all_atoms, chain_ids = "HL"):
    atom_index = 0
    pdb_lines = []
    record_type = "ATOM"
    seq = numbered_sequences[chain_ids[0]] + numbered_sequences[chain_ids[1]]
    chain_index = [0]*len(numbered_sequences[chain_ids[0]]) + [1]*len(numbered_sequences[chain_ids[1]])
    chain_id = chain_ids[0]

    for i, amino in enumerate(seq):
        for atom in atom_types:
            if atom in residue_atoms[amino[1]]:
                j = residue_atoms[amino[1]].index(atom)
                pos = all_atoms[i, j]
                if pos.mean() != pos.mean():
                    continue
                name = f' {atom}'
                alt_loc = ''
                res_name_3 = restype_1to3[amino[1]]
                if chain_id != chain_ids[chain_index[i]]:
                    chain_id = chain_ids[chain_index[i]]
                occupancy = 1.00
                b_factor = 0.00
                element = atom[0]
                charge = ''
                # PDB is a columnar format, every space matters here!
                atom_line = (f'{record_type:<6}{atom_index:>5} {name:<4}{alt_loc:>1}'
                             f'{res_name_3:>3} {chain_id:>1}'
                             f'{(amino[0][0]):>4}{amino[0][1]:>1}   '
                             f'{pos[0]:>8.3f}{pos[1]:>8.3f}{pos[2]:>8.3f}'
                             f'{occupancy:>6.2f}{b_factor:>6.2f}          '
                             f'{element:>2}{charge:>2}')
                pdb_lines.append(atom_line)
                atom_index += 1

    return "\n".join(pdb_lines)

In [66]:
print(prediction.numbered_sequences.keys())

for chain, seq in prediction.numbered_sequences.items():
    print("\nChain:", chain)
    print("Type:", type(seq))
    print("Length:", len(seq))
    print("First entries:", seq[:5])

dict_keys(['H', 'L'])

Chain: H
Type: <class 'list'>
Length: 126
First entries: [((2, ' '), 'V'), ((3, ' '), 'Q'), ((4, ' '), 'L'), ((5, ' '), 'Q'), ((6, ' '), 'E')]

Chain: L
Type: <class 'list'>
Length: 0
First entries: []